### PR TITLE
gluon-mesh-vpn-fastd: add public key to nodeinfo provider

### PR DESCRIPTION
**Pull request by mweinelt**
We are using the fastd exporter (https://github.com/freifunk-darmstadt/fastd-exporter) for Prometheus statistics and since the only stable key to link the graphs with other respondd data is the public key I propose adding it to the nodeinfo response.

Gotcha: The code is largely duplicated from the `get_fastd_version` function above it.

### CODE REVIEW

**Comment by mweinelt** [comment]
By default if fastd was not enabled the key is set to:
```
fastd.mesh_vpn.secret='generate'
```

Calling `/etc/init.d/fastd show_key mesh_vpn` will generate a secret.

Is this an issue?

**Comment by NeoRaider** [comment]
@mweinelt The code should work similar to the info page in the "Advanced settings".

Hmm, I thought there was already an issue for this addition, but I can't find it right now. I don't really like the idea of adding the public key, as it makes it easier to correlate nodes and VPN sessions "from the outside", which might be undesirable because of privacy concerns.

**Comment by rotanid** [comment]
> which might be undesirable because of privacy concerns
also thought this to be the reason it is hard to get this correlation at the moment. 
the thing is though, it should be easy at least for the operator of the vpn gateway. maybe there is a trick so at least these operators can correlate easier?

**Comment by mweinelt** [comment]
Pubkey is now being advertised on the condition that the mesh-vpn fastd instance is enabled.

Via https://github.com/freifunk-gluon/gluon/blob/master/package/gluon-web-admin/files/lib/gluon/web/view/admin/info.html#L16-L17

**Comment by rotanid** [comment]
i would really like to know how this would affect the privacy, a real world example with explicitly naming the potential "attacker" and what would be gained and how

**Comment by mweinelt** [comment]
@rotanid From my (probably limited) understanding of the issue, here's my take on things:

- The node is uniquely identifiable by it's mac address.
- The public key is always part of the fastd handshake.

Putting both together client traffic and tunnel traffic can be correlated and the traffic flow can then, probably by a nation state attacker, be attributed to the actual IP address of the node.

**Comment by NeoRaider** [comment]
I don't think we should add Gluon-specific fields to non-Gluon UCI sections. It would be better to just get the value directly from the site in the respondd provider.

**Comment by mweinelt** [comment]
Updated to not use UCI and use the value from the site instead, defaulting to `true`.

**Comment by T-X** [comment]
I'm probably missing some basic cryptography knowledge, but concerning the node correlation:

Would it be an option to encrypt the handshake messages a fastd peer A sends to B with the public key of B? That way, only who has the private key of B is able to proof that the message was encrypted to B?

(what also came to my mind, probably for another ticket: should we enable the IPv6 privacy extension on br-wan? Otherwise we probably leak a node's MAC address via the IPv6 header of a fastd packet anyways)

**Comment by NeoRaider** [comment]
@T-X 
Might be possible, but likely fatal for handshake performance, and the attack scenario is unclear. Also, I don't intend to change the handshake protocol of fastd any time soon.

Privacy extension support should have a way to opt-out, and is AFAIK not supported by netifd/odhcp6c at all at the moment.

**Comment by NeoRaider** [comment]
Merged (I changed the doc part a bit).

**Comment by rotanid** [comment]
here's the link to the merged commit for future reference: 42763d21dc6854e720cd2d8a58ae5fbf5b444f73

**Pull request closed without merging**
