### PR TITLE
docs,LICENSE: Drop copyright years

### PR DESCRIPTION
**Pull request by AiyionPrime**
This should be backported before we release anything in 2023, no?

### CODE REVIEW

**Comment by mweinelt** [comment]
https://hynek.me/til/copyright-years/

**Comment by AiyionPrime** [comment]
Fine by me; leaving 2022 in is not.
@mweinelt do you favor any variants the article and linked sources suggest over others?

`2015-present` or `2015`? or leave the note out alltogether like curl did?

**Comment by rotanid** [comment]
also interested in @NeoRaider s opinion.
i think it's a good idea to drop the "current" year and have no strong opinion on the variants.

**Comment by AiyionPrime** [comment]
Maybe we can simply merge and backport this and open an issue which can then wait on more opinions on how we'd like to got on in the future.
It was not my intention for this to slow down the release.

**Comment by NeoRaider** [comment]
I'd get rid of the years altogether.

**Comment by AiyionPrime** [comment]
Done.

**Comment by AiyionPrime** [comment]
Any opinions on backporting this?

**Pull request merged**
