### PR TITLE
Add support for ZBT-WG3526-32M

### PR DESCRIPTION
**Pull request by jplitza**
These are (almost) the devices that @corny has shipped in from China.

While those have 32 MB Flash, the image only works with 16 MB currently. They have 512 MB RAM and support 802.11ac.

The image currently has a [problem with rebooting because of the flash chip](http://lists.infradead.org/pipermail/linux-mtd/2016-November/070368.html), thus it would even be broken if the target wouldn't be as a whole. Nonetheless, I would like to challenge the note by @NeoRaider left in `targets/targets.mk`:
```
$(eval $(call GluonTarget,ramips,mt7621)) # BROKEN: No AP+IBSS support, 11s has high packet loss
```
I do currently operate the device in AP+IBSS mode. Thus, this either seems to be fixed or a restriction of the only other device in that subtarget (d-link-dir-860l-b1). However, throughput through IBSS is quite low (11 MBit/s net).

Another caveat is that seemingly random, there are stack traces like these in the log:
```
[ 2739.120000] ------------[ cut here ]------------
[ 2739.120000] WARNING: CPU: 0 PID: 0 at /home/jplitza/Code/freifunk/site/gluon/build/ramips-mt7621/openwrt/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2_gluon-ramips-mt7621/linux-ramips_mt7621/mt76-2016-08-25/mt7603_mac.c:403 mt7603_mac_fill_rx+0x2c4/0x3cc [mt7603e]()
[ 2739.140000] Modules linked in: iptable_nat nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack macvlan iptable_raw iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 sch_fq em_nbyte sch_prio sch_pie act_ipt em_meta sch_gred sch_dsmark sch_teql sch_codel em_cmp em_text sch_htb sch_sfq sch_red act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc mt7603e mt76x2e mt76 mac80211 cfg80211 compat batman_adv libcrc32c ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables dummy tun leds_gpio act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug crc16 crc32c_generic crypto_hash
[ 2739.250000] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W      3.18.44 #7
[ 2739.250000] Stack : 00000000 00000004 00000006 00000001 00000000 00000000 00000000 00000000
[ 2739.250000] 	  803e56e2 00000041 00000000 00000000 00000000 8039f5e0 8033510c 8039f243
[ 2739.250000] 	  00000000 00000000 803e4468 8039f5e0 8f2dd9c0 0000007c 80410000 8005ab6c
[ 2739.250000] 	  00000001 8002982c 803a3760 803a3764 80338dc4 8038dbf4 8038dbf4 8033510c
[ 2739.250000] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 2739.250000] 	  ...
[ 2739.250000] Call Trace:
[ 2739.250000] [<800167ac>] show_stack+0x50/0x84
[ 2739.250000] [<801638e4>] dump_stack+0x88/0xc0
[ 2739.250000] [<800299a8>] warn_slowpath_common+0x84/0xb4
[ 2739.250000] [<80029a60>] warn_slowpath_null+0x18/0x24
[ 2739.250000] [<8ec5bd54>] mt7603_mac_fill_rx+0x2c4/0x3cc [mt7603e]
[ 2739.250000] [<8ec5ab10>] mt7603_queue_rx_skb+0xb8/0x100 [mt7603e]
[ 2739.250000] [<8f21cd18>] mt76_dma_attach+0x890/0x9cc [mt76]
[ 2739.250000] 
[ 2739.330000] ---[ end trace ad9914c04a5b78a4 ]---
[ 2739.340000] ------------[ cut here ]------------
[ 2739.340000] WARNING: CPU: 0 PID: 0 at /home/jplitza/Code/freifunk/site/gluon/openwrt/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2_gluon-ramips-mt7621/linux-ramips_mt7621/compat-wireless-2016-06-20/net/mac80211/rx.c:4124 ieee80211_rx_napi+0xb4/0x8cc [mac80211]()
[ 2739.360000] Modules linked in: iptable_nat nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE ebtable_nat ebtable_filter ebtable_broute xt_time xt_tcpudp xt_state xt_quota xt_pkttype xt_physdev xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_LOG xt_CT nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack macvlan iptable_raw iptable_mangle iptable_filter ip_tables ebtables ebt_vlan ebt_stp ebt_snat ebt_redirect ebt_pkttype ebt_mark_m ebt_mark ebt_limit ebt_ip6 ebt_ip ebt_dnat ebt_arpreply ebt_arp ebt_among ebt_802_3 sch_fq em_nbyte sch_prio sch_pie act_ipt em_meta sch_gred sch_dsmark sch_teql sch_codel em_cmp em_text sch_htb sch_sfq sch_red act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_hfsc mt7603e mt76x2e mt76 mac80211 cfg80211 compat batman_adv libcrc32c ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables dummy tun leds_gpio act_police cls_basic sch_tbf sch_ingress gpio_button_hotplug crc16 crc32c_generic crypto_hash
[ 2739.470000] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W      3.18.44 #7
[ 2739.470000] Stack : 00000000 00000004 00000006 00000001 00000000 00000000 00000000 00000000
	  803e56e2 00000041 00000000 00000000 00000000 8039f5e0 8033510c 8039f243
	  00000000 00000000 803e4468 8039f5e0 8f2dd9c0 0000000c 80410000 8005ab6c
	  00000001 8002982c 803a3760 803a3764 80338dc4 8038dbb4 8038dbb4 8033510c
	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
	  ...
[ 2739.470000] Call Trace:
[ 2739.470000] [<800167ac>] show_stack+0x50/0x84
[ 2739.470000] [<801638e4>] dump_stack+0x88/0xc0
[ 2739.470000] [<800299a8>] warn_slowpath_common+0x84/0xb4
[ 2739.470000] [<80029a60>] warn_slowpath_null+0x18/0x24
[ 2739.470000] [<8eca3cdc>] ieee80211_rx_napi+0xb4/0x8cc [mac80211]
[ 2739.470000] [<8f21d538>] mt76_rx_complete+0x78/0x104 [mt76]
[ 2739.470000] [<8f21cd2c>] mt76_dma_attach+0x8a4/0x9cc [mt76]
[ 2739.470000] 
[ 2739.550000] ---[ end trace ad9914c04a5b78a5 ]---
```

However, they do not seem to impact operation.

**Edit**: Hm, maybe they do for 2.4 GHz. I've only tested 5 GHz, but in 2.4 GHz, the graphs on the status page have holes (on both sides of the connection):
canvas

### CODE REVIEW

**Comment by corny** [comment]
The ZBT-WG3526 with 16M has no issues with rebooting. Only the 32M version (aka [Digineo AC1200 Pro](https://github.com/lede-project/source/pull/509) has this problem. We are trying to solve this issue with the MTD maintainers. Unless it is solved we can use this hotfix: https://gist.github.com/dmke/d389bc364b3f73f525076eaee0019dc1

**Comment by NeoRaider** [comment]
Besides the issues mentioned here, I've had problems with OpenWrt CC on my ZBT-WG3526 (16M) (unexplainable segfaults), I had hoped to switch to LEDE soon-ish to avoid having to debug this on CC.

Well, that was before we got unexplainable segfaults in LEDE on most of ar71xx... ( https://bugs.lede-project.org/index.php?do=details&task_id=251 )

**Comment by corny** [comment]
Now I only get a `gluon/output/images/factory/gluon-ffhb-2016.2.1+ac1200exp1-d-link-dir-860l-b1.bin` but I expect the sysupgrade image instead. Do you have a hint for me?

**Comment by corny** [comment]
I try `$(eval $(call GluonProfile,...))`

**Comment by corny** [comment]
There is a [blocking issue](https://github.com/openwrt/mt76/issues/62) with the mt7603 driver. I sent a device for debugging to @nbd168 and probably @NeoRaider will take a look at it.

**Comment by jordipalet** [comment]
I think I'm having the same issue, or related.

Using LEDE Reboot 17.01.0-rc2 r3131-42f3c1f / LuCI lede-17.01 branch (git-17.032.85243-5f80115).

Almost every day I get this:

[ 3502.270000] ------------[ cut here ]------------
[ 3502.270000] WARNING: CPU: 1 PID: 2741 at /build/lede-17.01/slaves/phase1/ramips_mt7621/build/build_dir/target-mipsel_24kc_musl-1.1.16/linux-ramips_mt7621/mt76-2017-01-31-3c8caafc/mt7603_mac.c:1207 0x8edfd31c [mt7603e@8edf8000+0x68a0]()
[ 3502.290000] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_mppe ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ums_usbat ums_sddr55 ums_sddr09 ums_karma ums_jumpshot ums_isd200 ums_freecom ums_datafab ums_cypress ums_alauda ts_kmp ts_fsm ts_bm slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat_ftp nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_ftp iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt sch_cake nf_conntrack sch_teql em_nbyte sch_pie sch_red sch_gred sch_dsmark cls_basic act_ipt sch_prio em_meta em_text sch_codel sch_sfq act_police em_cmp sch_fq act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress ledtrig_usbport mt7603e mt76x2e mt76 mac80211 cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables msdos ip_gre gre ifb sit tunnel6 tunnel4 ip_tunnel tun vfat fat nls_utf8 nls_iso8859_1 nls_cp437 sha1_generic ecb mmc_block usb_storage sdhci_pltfm sdhci mtk_sd mmc_core ohci_platform ohci_hcd ehci_platform ehci_hcd ext4 jbd2 mbcache crc32c_generic leds_gpio xhci_mtk xhci_plat_hcd xhci_pci xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug usbcore nls_base usb_common
[ 3502.430000] CPU: 1 PID: 2741 Comm: kworker/u8:0 Not tainted 4.4.47 #0
[ 3502.440000] Workqueue: phy1 0x8edfd11c [mt7603e@8edf8000+0x68a0]
[ 3502.440000] Stack : 8d32ab00 80420000 803a193c 000004b7 00000000 00000000 00000000 00000000
[ 3502.440000] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3502.440000] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3502.440000] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3502.440000] 	  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 3502.440000] 	  ...
[ 3502.480000] Call Trace:[<80016448>] 0x80016448
[ 3502.480000] [<80016448>] 0x80016448
[ 3502.490000] [<801b4138>] 0x801b4138
[ 3502.490000] [<8002bf50>] 0x8002bf50
[ 3502.490000] [<8edfd31c>] 0x8edfd31c [mt7603e@8edf8000+0x68a0]
[ 3502.500000] [<8002c008>] 0x8002c008
[ 3502.500000] [<8edfd31c>] 0x8edfd31c [mt7603e@8edf8000+0x68a0]
[ 3502.510000] [<8000bea0>] 0x8000bea0
[ 3502.510000] [<8003f100>] 0x8003f100
[ 3502.520000] [<8003fffc>] 0x8003fffc
[ 3502.520000] [<8003fd24>] 0x8003fd24
[ 3502.520000] [<8003fd24>] 0x8003fd24
[ 3502.530000] [<800447b4>] 0x800447b4
[ 3502.530000] [<800446dc>] 0x800446dc
[ 3502.530000] [<80005478>] 0x80005478
[ 3502.540000] 
[ 3502.540000] ---[ end trace f807dc80e13a4e0e ]---

**Comment by corny** [comment]
@nbd168 told me the mt7603 driver is just a prototype. This issue should be closed until a complete driver exists.

**Comment by jordipalet** [comment]
Thanks @corny, understood. May be just disabling this Wireless will make the rest of the system stable meanwhile?

By the way, do you know how to check if I've the 16 or 32 Mb flash system? A dmesg shows:
[    2.430000] m25p80 spi32766.0: using chunked io (size=32)
[    2.430000] m25p80 spi32766.0: w25q128 (16384 Kbytes)
so I suspect that it is a 16, but not sure if it is being detected correctly.

Other issues I've with this product, in case you know:
1) Led's seems to not work (Wireless)
2) Not sure also the sdhci is working, can't get SD cards formated and mounted, and they work in other systems
3) USB pendrives seem to be corrupted from time to time, I guess it may be related to the system rebooting because the mt7603 driver, but not sure ...

**Comment by corny** [comment]
@jordipalet Disabling the wireless should make the system stable. Please keep in mind that there are issues with the drivers of both radios (2.4 and 5 Ghz).

**Comment by rotanid** [comment]
this PR needs a rebase - also, it would be better to first include support for the ZBT-WG3526 (which shouldn't have major issues anymore) and do a separate PR for the Digineo AC1200 Pro

**Comment by rotanid** [comment]
just noticed the 32M device has been renamed in LEDE:
https://git.lede-project.org/?p=source.git;a=commit;h=3cfc909c54c07d5a24d9a1a7496142b82d580878

**Comment by rotanid** [comment]
the 16M version is now supported in gluons master branch.

**Comment by jordipalet** [comment]
I understood that the 16Mb version was working fine. What we still have not solution is the 2.4 radio problems?

**Comment by rotanid** [comment]
i only did a speedtest with a client and both frequencies worked fine.
it's no device with enormous speeds, but you wouldnt expect that from a "2x2" device.
i got around 70 MBit/s with my phone over 2.4 GHz (over 5GHz my ISP was the limit)
maybe the speed issues with 802.11s still exist, i didn't test this.

**Comment by jordipalet** [comment]
It was not a speed problem, but actually the stack traces, and occasionally making the system reboot.

**Comment by rotanid** [comment]
yeah, see those stacktraces too. so it's still not ideal, at least with the status in lede-17.01 branch of LEDE

**Comment by rotanid** [comment]
this PR is superseded by #1296 , i'm closing it

**Pull request closed without merging**
