### PR TITLE
gluon-*batman-adv: Also list neighbors with non-best direct link

### PR DESCRIPTION
**Pull request by ecsv**
Links between two direct neighbors are not always the best route between
these devices. The flag BATADV_ATTR_FLAG_BEST would not be set for these
originator entries and the respondd module would just ignore this entry.

This causes missing links in meshviewer and similar tools. And when the
link quality is nearly equal and but fluctuates slightly, these links will
from time to time appear and disappear on the map.

Or ff these neighbors are not accepted and returned to the status page then
some of the neighbor entries will show a name, (acceptable) signal strength
and mac address but no TQ value.

### CODE REVIEW

**Comment by CodeFetch** [comment]
@ecsv The only problem I see is that the function is called "originators" and originators are per definition the best next hop. We need to add a flag to the respondd-data and visualize it on the status page to make clear "this is not a best next hop". Not showing the nodes on the status page and the map is of course wrong. Thank you for pointing this issue out.

**Comment by ecsv** [comment]
Ehrm, since when are originators best next hops?

**Comment by CodeFetch** [comment]
Sorry I just edited it "best next hop to something"

**Comment by ecsv** [comment]
> Sorry I just edited it "best next hop to something"

I seem to have a different definition for that. https://www.open-mesh.org/projects/open-mesh/wiki/BATMANConcept

**Comment by CodeFetch** [comment]
@ecsv Okay thus the definition of originators is still correct with your changes, but BATADV_ATTR_FLAG_BEST does mean it is the best entry to this originator. 
Shouldn't there be a best entry for every originator? Doesn't removing this flag mean you get duplicate originator entries?

**Comment by ecsv** [comment]
Problem is here that we want to have only the information for the neighors. So it goes through the list of originators, compares the originator and next-hop mac address and only accepts entries which have equal originator and next-hop entry. Before that (and even when the debugfs file was parsed) only the best next hop entry was checked.

I've reimplemented the behavior of the debugfs parser when I wrote the netlink part and made a note that this behavior has to be changed (because it seems to be wrong).... and then I forgot about it. Luckily, I've observed this weird behavior again and thus prepared the changes in this PR.

PS: Keep in mind that the debugfs file had one line per originator and the mac address after the originator was the best next hop.

**Comment by CodeFetch** [comment]
@ecsv Why do you give me a thumbs down emoji? Don't you know Microsoft uses that for rating.

**Comment by CodeFetch** [comment]
@ecsv Can you please just add something like `json_object_object_add(obj, "best", json_object_new_boolean(attrs[BATADV_ATTR_FLAG_BEST]);` to respondd.c?

**Comment by T-X** [comment]
Looks like a good idea to me. This will give valuable extra information regarding the robustness / redundancy / potentiall fallback links in the topology. Code looks fine, too.

**Comment by T-X** [comment]
What confused me a bit, which is not directly related to this patch, is the `` if (memcmp(orig, dest, 6) != 0)``.  A check which seems to have been part of the debugfs version earlier already via a ``if (strcmp(mac1, mac2))``. Had to read the batman-adv code a few times concerning the neigh_node, wasn't sure whether that would play nicely with the secondary interface MAC. But it seems to work.

(I'm wondering whether it would be easier and more intuitive for users if we were adding a BATADV_ATTR_DIRECT_NEIGH attribute to batman-adv, which would be set to true if ``neigh_node->orig_node == orig_node in *_orig_dump_subentry(). So that userspace could check this flag instead of this memcmp())

**Comment by ecsv** [comment]
Was this now approved by @T-X or not? There is no status change in his review (still set to "waiting for review").

I will definitely not add the BATADV_ATTR_DIRECT_NEIGH flag in this PR. This is a thing which first has to go to upstream first.

**Comment by rotanid** [comment]
@ecsv let's treat the "code looks fine, too" as an ACK.
i'm merging.

**Pull request merged**
