### PR TITLE
Rename Altitude to Storey

### PR DESCRIPTION
**Pull request by rubo77**
This replaces the unintuitive value "altitude" with Storey, which is either known, or can be aproximated by imaginary stroeys of 3m per storey

TODO: 

- [ ] migtrate script, that fills the field with a third of the old altitude value, (if given)
- [ ] french translation

### CODE REVIEW

**Comment by kb-light** [comment]
I see the same problems as @NeoRaider mentioned already in #581. For example at University we have a building, where storey 2 is the ground-floor (others starts with storey 0).
Additionally the router can be placed on the floor or be ceiling-mounted.  And if you have some outdoor installation, it is maybe more complicated to reverence to a storey, than to some altitude.
So I think "storey" is more complicated than altitude and I see no difference to "altitude in meters above streetlevel" if you can "aproximate" it with 3m.

In my opinion the goal should be to get an easy and accurate method for measuring the altitude, for example with a navigation app on your smartphone. And not trying to rename "altitude" every few month.

**Comment by rubo77** [comment]
there is no easy way to measure the altitude with a navigation app on your smartphone, because they are incredibly inaccurate (several 10m inaccurate) and another outdoor option won't be there for a normal user.

So there is either:

 - no altitude information at all
 - an **only informative**, but not physical precise, information to place routers inside a house relative to each other

I think the latter is a very useful information if you place more than one router in the same building.

**Comment by kb-light** [comment]
The first is the way we actually proceed. The altitude field is disabled within the config mode, because we see the problem with actually not well defined altitude, too.
The second might by interesting, when searching the router, but it is nor usable for calculating distances between the routers.

I agree, that 10m is not accurate enough. Currently I am thinking about getting the altitude by some map services similar to lat/lon, which was already mentioned by you in #453. Then the owner has to estimate the altitude above "streetlevel" and add it to the value. If the steetlevel is not well defined in some point, one can chose an other location as reference.

**Comment by Adorfer** [comment]
Nur weil es einige Gebäude an Hanglage gibt muss man das Feature doch nicht für alle ruinieren.
Und da die meisten Gebäude einen postalischen Haupteingang haben (der als EG/L0 zählt), sollte das mit der Etagenzählung "in OSM-Stil" eigentlich kein Problem darstellen. 
Wobei da jetzt bestimmt jemand mit einem Wohnblock mit mehreren Hausnummern und Eingängen am Hang kommt...

Fakt ist, dass sich die Höhe mit bezahlbarem GPS nicht sauber ermitteln lässt, die Abweichung ist etwa um Faktor 4 schlechter als die in lat/lon. Und da freut man sich über 5m Genauigkeit. In der Praxis weist die Höhe eine Abweichung von minimal +/-10 m auf, tendenziell eher 20m, wenn man nicht "runherum" freie Sicht auf den Horizont hat.
Wenn also zwei Leute im gleichen Haus nebeneinander je einen Node aufstellen, dann stehen die mit etwas Pech auf 80m und 120m, bei 20m seitlichem Abstand.

**Comment by jplitza** [comment]
I think two things are obvious:
* There are people unhappy with the current semantics of the height field, wanting to change it to something different.
* There are people happy with the current semantics of the height field, not wanting to change it to something different.

Thus, we won't reach consensus on a Gluon-wide approach. Instead, I propose to rename the field to something neutral (although "altitude" already is kind of neutral, according to Wikipedia, and "height" has some ISO meanings as well…) and move all descriptional messages for this field into site translation files. That way, every community can decide on its own what semantics this field should have and how to best describe it.

As that is basically also what @tcatm and @NeoRaider proposed in #581, I think it is save to say the current PR won't get merged. Thus, I'll close it.

**Comment by rubo77** [comment]
OK, I created #873

**Pull request closed without merging**
