### PR TITLE
docs: examples: remove haveged from GLUON_SITE_PACKAGES

### PR DESCRIPTION
**Pull request by jluebbe**
OpenWRT 19.07 enables urngd by default, so haveged is redundant.

### CODE REVIEW

**Comment by mweinelt** [comment]
There are a few more places where haveged is mentioned, not entirely sure removing is as easy as removing it here. Also we need to make urngd is started early enough in the setup mode to have a working key generation for fastd et al.

```
❯ rg haveged
docs/site-example/site.mk
26:GLUON_SITE_PACKAGES := haveged iwinfo

docs/multidomain-site-example/site.mk
32:GLUON_SITE_PACKAGES := haveged iwinfo

package/gluon-autoupdater/files/usr/lib/autoupdater/abort.d/90gluon-autoupdater
7:start_enabled haveged

package/gluon-autoupdater/files/usr/lib/autoupdater/download.d/10gluon-autoupdater
7:stop haveged

package/gluon-setup-mode/files/lib/gluon/setup-mode/rc.d/S13haveged
3:if [ -x /etc/init.d/haveged ] && /etc/init.d/haveged enabled; then
4:	. /etc/init.d/haveged
```

**Comment by jluebbe** [comment]
I left the other places as they are, as my understanding is that they are needed to handle it correctly if a user decides they still want haveged.

**Comment by mweinelt** [comment]
The autoupdater scripts probably need a check, whether the init script even exists. There might also be the need to add such scripts for urngd.

**Comment by NeoRaider** [comment]
I think we should replace the references to haveged wuith urngd in the autoupdater code, I see no reason to keep supporting haveged.

**Comment by jluebbe** [comment]
> I think we should replace the references to haveged with urngd in the autoupdater scripts, I see no reason to keep supporting haveged.

I've replaced haveged with urngd  in gluon-setup-mode and gluon-autoupdater as well.

**Pull request merged**
