### PR TITLE
French translation: WLAN -> Wi-Fi

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by NeoRaider** [comment]
A quick lookup in a dictionary gives me the spellings "wifi" and "WIFI", but not "Wi-Fi": https://dict.leo.org/franz%C3%B6sisch-deutsch/WLAN

**Comment by edeso** [comment]
i guess https://en.wikipedia.org/wiki/Wi-Fi is the proper spelling according to the alliance behind the standard.

..ede

**Comment by rubo77** [comment]
The french wikipedia page for "wifi" redirects to "wi-fi" too:

https://fr.wikipedia.org/wiki/wifi

**Comment by rubo77** [comment]
also French telecom providers use this term:

https://www.orange.com/ -> search for "wifi" there

**Comment by NeoRaider** [comment]
@edeso As this is about spelling of the French word and not about the standard, that's not a very strong argument.

@rubo77 Well, that Wikipedia page starts with "A Wi-Fi, also spelled wifi, [...]"... Nevertheless, I've merged it like this, as both spellings seem to be in use.

**Pull request merged**
