### PR TITLE
RFC: Switch from batman-adv debugfs to netlink

### PR DESCRIPTION
**Pull request by ecsv**
The batadv debugfs requires large memory blocks to write the text debug tables. This is inefficient for large tables like the global translation table or the originators table.

The memory requirement can be reduced by using netlink. It copies smaller packets in a binary format to the userspace program. gluon can therefore parse larger originator tables without causing an OOM on systems which are tight on memory.

This is only an RFC because it may collide with the LEDE port, batman-adv-legacy support for netlink is missing and it would actually be nicer to update the openwrt-routing feed instead of having to use patches for it. The code is an updated version of what was already posted in #753

### CODE REVIEW

**Comment by NeoRaider** [comment]
For the update to batman-adv 2016.4, I would update the *openwrt-routing* feed to the current master (as soon as the 2016.4-maint PR is in).

**Comment by ecsv** [comment]
Ok, sounds good. I have now updated the RFC to only include the patches which are currently missing in openwrt-routing

**Comment by belzebub40k** [comment]
Just for completeness. gluon-radv-filterd #838 is also using debugfs at the moment.

**Comment by jplitza** [comment]
Having a set of three files (netlink.c, netlink.h, batman_adv.h) in every package (currently: 3 with #838) that queries batman-adv seems suboptimal. I didn't have a closer look yet, how difficult would it be to have a library that handles querying the netlink interface and package it separately?

**Comment by ecsv** [comment]
It is basically a single function (netlink_query_common) and a package specific definition for batadv_netlink_policy. The batman_adv.h is a linux kernel uapi header which is just not yet available in the kernel from gluon. I personally will not create a library for that.

**Comment by jplitza** [comment]
I see. Wouldn't it make sense to include the batman_adv.h as a patch against the kernel then?

**Comment by ecsv** [comment]
The requested changes were pushed. Now it is not enough to do a "make clean" but instead a complete toolchain rebuild is required to get linux/batman_adv.h (basically to recreate toolchain/kernel-headers).

**Comment by NeoRaider** [comment]
Hmm, I'd prefer to add a batman-adv-provided include path to the TARGET_CFLAGS of the relevant packages rather than patching it into the kernel, otherwise it will be another patch to carry over when switching to LEDE.

**Comment by ecsv** [comment]
I personally will not do that.

**Comment by NeoRaider** [comment]
@ecsv, do you still have the previous version of this branch, with each package including the *batman_adv.h* itself? I'd be willing to merge it like that (after all, including a copy of required UAPI headers that can't be taken for given is quite common).

**Comment by ecsv** [comment]
@NeoRaider I have it in https://github.com/FreifunkVogtland/gluon/tree/batadv-netlink-perpackage . But there is still the batman-adv-legacy change missing in https://github.com/freifunk-gluon/packages/commits . I personally would recommend not to merge it until it is rebased on a patch which imports the gluon-packages with the batman-adv-legacy import.

I don't know what your plans are for upgrading the batman-adv-legacy in gluon-packages.

**Comment by NeoRaider** [comment]
Yes, that makes sense. I have the update staged locally, I'll see that I can get it tested and pushed soon.

**Comment by NeoRaider** [comment]
Both batman-adv versions have been updated to a version with netlink support.

**Comment by ecsv** [comment]
Looks like you've broken reference counting in batadv_send_outstanding_bcast_packet. See my original patch for updating to 2016.4 for details

**Pull request closed without merging**
