### PR TITLE
patch for iw to enable scan output for IEEE802.11s

### PR DESCRIPTION
**Pull request by 2tata**
Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>

### CODE REVIEW

**Comment by NeoRaider** [comment]
We don't really need the mesh cabapilities, do we? The mesh ID should be enough AFAICT.

**Comment by 2tata** [comment]
On 03/23/17 12:26, Matthias Schiffer wrote:
> We don't really need the mesh cabapilities, do we? The mesh ID should be enough AFAICT.
> 

Right, the cabapilities can be dropt. For the hoodselector, ID is enough.

cheers
Tarek

**Comment by 2tata** [comment]
done

cheers
Tarek

**Comment by NeoRaider** [comment]
Thanks, I've pushed a similar change to LEDE and updated *modules*. We really want to avoid adding patches in Gluon when we can.

**Pull request closed without merging**
