### PR TITLE
docs: update targets

### PR DESCRIPTION
**Pull request by bobcanthelpyou**
target ipq806x was marked as broken because of #1505 
target sunxi was renamed to sunxi-cortexa7 via 210d97c53eb147ad9519118634c71e28eace4694

### CODE REVIEW

**Comment by bobcanthelpyou** [comment]
How to remove `ipq806x` in the old docs?
* https://gluon.readthedocs.io/en/v2018.2/
* https://gluon.readthedocs.io/en/v2018.1.4/
* https://gluon.readthedocs.io/en/v2018.1.3/
* https://gluon.readthedocs.io/en/v2018.1.2/
And how to rename `sunxi` in 
* https://gluon.readthedocs.io/en/v2018.2/

**Comment by CodeFetch** [comment]
Don't rewrite the history. What I really don't understand is that you didn't file a bug report to ath10k-ct.

**Comment by bobcanthelpyou** [comment]
Than it might be okay as it is.

**Comment by rotanid** [comment]
@bobcanthelpyou we try to always link like this:
https://gluon.readthedocs.io/en/v2018.2.x/releases/v2018.2.html
https://gluon.readthedocs.io/en/v2018.1.x/releases/v2018.1.3.html
this way, a change to the docs can be done even for older release notes by committing to the respective branch.
Feel free to provide fixes to other branches (but everything has to be fixed in master first).
if your change is cherry-pickable to another branch (so the same change applies for multiple branches) simply write this in your pull request.

**Comment by bobcanthelpyou** [comment]
@rotanid that could mean splitting the commit into two and cherry-pick these commits to different branches

ipq806x -> v2018.2.x && v2018.1.x
sunxi-cortexa7 -> v2018.2.x

**Comment by rotanid** [comment]
feel free :)

**Comment by bobcanthelpyou** [comment]
The commit b02d197279ddca887fba53111f8d7ad480eff8e9 could be merge to master and cherrypicked to v2018.2.x and v2018.1.x (if that could be useful)

The commit c7f733959bfadefd3d8bd7b28a24d5e0b00ee46a could be merge to master and cherrypicked to v2018.2.x (if that could be useful)

**Comment by rotanid** [comment]
thanks. cherry-pick to v2018.1.x wasn't as easy though ;)

**Pull request merged**
