### PR TITLE
ar71xx-generic: add support for TP-Link CPE210 v3.20

### PR DESCRIPTION
**Pull request by SmithChart**
This pull request backports changes from OpenWrt into the v2019.1.x maintainance branch that allow us to use the CPE210 v3.2.

The PR contains two parts:
a) Allow the SPI-NOR driver to bind for the NOR used inside the CPE210 V3.2. This change was made for 4.19 and 4.14 in OpenWRT upstream. This patch packports the crucial change from there to 4.9 (that is used for ar71xx-generic in v2019.1.x).
The upstream commit was:
https://github.com/openwrt/openwrt/commit/359f5e539036db4f7ac69a6d1c3fb7fe70266ffd

b) Add the needed sugar to the TP-Link safeloader.
The upstream commit was:
https://github.com/openwrt/openwrt/commit/4a2380a1e778a8f8e0bfb0a00f2996ed0aab58d8

I hope this kind of backporting of Upstream Changes to older branches is OK. This way this hardware can be supported in all the communities that still rely on v2019.1.x to be maintained a bit longer.

This PR replaces the following PRs done by Parabol1337:
https://github.com/freifunk-gluon/gluon/pull/2123
https://github.com/freifunk-gluon/gluon/pull/2124 (This one is still open but can be closed now.)

Also Parabol1337 has tested this changes on his CPE210 v3.2.

### CODE REVIEW

**Comment by blocktrron** [comment]
Correct me if I'm wrong, but this seems to not be part of OpenWrt 19.07 and therefor not Gluon master / v2020.2.x?

If so, this has to be backported there prior to v2019.x.

**Comment by SmithChart** [comment]
I have checked in OpenWRT below the following module-reference in <v2020.2.1>:
```
OPENWRT_REPO=https://github.com/openwrt/openwrt.git
OPENWRT_BRANCH=openwrt-19.07
OPENWRT_COMMIT=5af8da37870dc05dbe2e57e04be714b80f4aa21d
```
a) is in: https://github.com/openwrt/openwrt/commit/359f5e539036db4f7ac69a6d1c3fb7fe70266ffd
b) is in: https://github.com/openwrt/openwrt/commit/fba22d89a918fa0e7dfc457cb3a6f43a1e08a8ed

Both are well below the current OpenWRT state in v2020.2.1. So they should already be in there. Or am I mssing a bit here?

**Comment by blocktrron** [comment]
@SmithChart Sorry, I've missed this somehow. So this is ready to be merged IMHO.

**Review by blocktrron — APPROVED** [review]

**Comment by rotanid** [comment]
i wonder why these communitites "depending" on the v2019.1.x branch did not help with testing in #2104 ?
are you aware, that Gluon will stop maintaining this branch at the end of this year?
anyway, merging...

**Comment by rotanid** [comment]
@SmithChart CI says your PR has an issue with one patch... please provide a fix for this.

/home/jenkins/workspace/gluon-ci_PR-2137/openwrt/target/linux/generic/pending-4.14/479-mtd-spi-nor-add-eon-en25qh64.patch

**Comment by rotanid** [comment]
@SmithChart sorry, we wanted to do the release, so we reverted this pull request.
feel free to open a new one if you got the merge issues resolved.

**Comment by SmithChart** [comment]
> @SmithChart sorry, we wanted to do the release, so we reverted this pull request.
> feel free to open a new one if you got the merge issues resolved.

Just stumbled over my changes being reverted in v2019.1.3. Oh, i am sorry. I missed that there was an issue with my changes after it has been merged. 
v2019.1x is out of support. I guess it does not make since to create a new PR?

**Comment by rotanid** [comment]
@SmithChart support has not ended yet, see https://github.com/freifunk-gluon/gluon/wiki/Release-life-cycle
so it's up to you

**Pull request merged**
