### PR TITLE
targets/ar71xx-generic: add WD MyNet N600/N750

### PR DESCRIPTION
**Pull request by kaechele**
Signed-off-by: Felix Kaechele <felix@kaechele.ca>

### CODE REVIEW

**Comment by kaechele** [comment]
obsoletes https://github.com/freifunk-gluon/gluon/pull/443

root@0090a9ac1b46:/# lua -e 'print(require("platform_info").get_image_name())'
wd-my-net-n750

**Comment by AiyionPrime** [comment]
@kaechele any chance you still own those two devices and could do a test for the current migration?

**Comment by kaechele** [comment]
I technically do but they are in my parent's basement in Germany. Didn't bring them when I moved to Canada. So not anytime soon 😅

**Comment by AiyionPrime** [comment]
Well, let me know when you visit them again. Seems like there are no other devices of this kind announcing themselves to gluon-census...

**Pull request merged**
