### PR TITLE
ar71xx: add support for TP-Link TL-WR840N v2

### PR DESCRIPTION
**Pull request by bobcanthelpyou**
TP-Link TL-WR840N v2: https://openwrt.org/toh/hwdata/tp-link/tp-link_tl-wr840n_v2

- [x] must be flashable from vendor firmware
  - [x] webinterface
  - [ ] tftp
  - [ ] other: <specify>
- [x] must support upgrade mechanism
  - [x] must have working sysupgrade
    - [x] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [x] must have working autoupdate
    *usually means: gluon profile name must match image name*
- wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
- wifi (if applicable)
  - [x] association with AP must be possible on all radios
  - [x] association with 802.11s mesh must be working on all radios 
  - [x] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led
    - [x] lit while the device is on
    - [x] should display config mode blink sequence 
(https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - radio leds
    - [x] should map to their respective radio
    - [x] should show activity
  - switchport leds
    - [x] should map to their respective port (or switch, if only one led present) 
    - [x] should show link state and activity
- [x] reset/wps button must return device into config mode
- [x] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)

### CODE REVIEW

**Comment by belzebub40k** [comment]
Isn't it counterproductive to add new devices with 4MB flash and 32MB RAM if we want to get rid of such devices in the future?

**Comment by rotanid** [comment]
@bobcanthelpyou so there's no problem with testing so far and only 2 things to test left, right?

@belzebub40k the current device integration policy allows 4/32 if no backport patch is necessary.
apart from that, the policy can be revisited at the next meeting or so.

**Comment by belzebub40k** [comment]
@rotanid ok, sorry I thought this decision was already made.

**Comment by bobcanthelpyou** [comment]
@rotanid I need to test `sysupgrade`, but already tested `autoupdate`.

**Comment by bobcanthelpyou** [comment]
`sysupgrade` and `firstboot` seems to be supported, too.

**Pull request merged**
