### PR TITLE
doku: add hint how to list multiple modules in modules

### PR DESCRIPTION
**Pull request by viisauksena**
maybe a link to a live example is also quiet nice to have,
especialy with the form of how to list a wanted packages was struggling

### CODE REVIEW

**Comment by viisauksena** [comment]
example out in the wild : 
https://cccfr.de/git/viisauksena/firmware/blob/support/modules
```
GLUON_SITE_FEEDS='v14tov15helper ssidchanger banner treatment'
PACKAGES_V14TOV15HELPER_REPO=https://github.com/viisauksena/gluon-v14tov15-helper.git
PACKAGES_V14TOV15HELPER_COMMIT=74b423c678b1d548c6e0ae6d02af1481cac102a7
PACKAGES_V14TOV15HELPER_BRANCH=master
PACKAGES_SSIDCHANGER_REPO=https://github.com/viisauksena/gluon-ssid-changer.git
PACKAGES_SSIDCHANGER_COMMIT=fb6b87ec0b68fee73e3b029be73a5949becc9425
PACKAGES_SSIDCHANGER_BRANCH=chaos-calmer
PACKAGES_BANNER_REPO=https://github.com/viisauksena/gluon-banner.git
PACKAGES_BANNER_COMMIT=880c01dcd2eac4dd420ec02827d056130efdcf38
PACKAGES_BANNER_BRANCH=master
PACKAGES_TREATMENT_REPO=https://github.com/viisauksena/gluon-treatment.git
PACKAGES_TREATMENT_COMMIT=3e3fd75199ebe44a63e0c47c07e3354c72b63d41
PACKAGES_TREATMENT_BRANCH=master
```

**Comment by NeoRaider** [comment]
The resulting file is very hard to read and understand. I think moving the documentation to the top and then having a complete example with two modules below would be nicer.

**Comment by viisauksena** [comment]
so, indeed very hard to understand, i make a complete rewrite inkl. example.

**Comment by tcatm** [comment]
I'd prefer this to be added to the documentation (as opposed to the sample config). The sample should stay as small and concise as possible while in the documentation the details for including modules can be explained in full length. Maybe add a extra chapter for them.

**Comment by viisauksena** [comment]
if you have clear ideas, just do it - i simply wanted this to state as clear as possible to use it directly. I think this (incl. example) will do the job.

**Comment by NeoRaider** [comment]
I've added some docs in 3f24aa248af5c616fc997c227a3c2807106c6429.

**Pull request closed without merging**
