### PR TITLE
ar71xx-generic: Fix flash layout and MAC addresses of Meraki MR12/MR16

### LINKED ISSUE #993: All Meraki MR16 have the same mac-address
Hi,
all Meraki MR16 have the same mac-address, after they're flashed with OpenWRT or for that sake Gluon.

LEDE have already found a fix for this. Is there a way to either integrate this patch into Gluon ?
Or is the move to LEDE so far progressed, that we can sort it that way ?

http://lists.infradead.org/pipermail/lede-dev/2016-October/003459.html

### PR DESCRIPTION
**Pull request by oleeander**
Fixes #993. This has so far only been verified to work with MR16.

Flashing:
```
# Upgrade from LEDE with manually set MAC address (remove Xs)
# eXrXaXsXe 0xbf080000 +0x20000; cXpX.Xb 0xbffd0000 0x80010066 0x20000; cXpX.Xb 0x80010000 0xbf080000 0x20000

tftpboot 0x80010000 gluon-mr16-squashfs-sysupgrade.bin; erase 0xbf0a0000 +0xf40000; cp.b 0x80010000 0xbf0a0000 0xf40000
setenv bootcmd bootm 0xbfda0000; saveenv; boot
```

### CODE REVIEW

**Comment by NeoRaider** [comment]
Thanks for your patch, looks good. As we're currently moving to LEDE, it would be nice if you could port you patch to LEDE and submit it there, so we don't accumulate downstream patches.

**Comment by oleeander** [comment]
Upstream pull-request: https://github.com/lede-project/source/pull/1408
For Gluon v2017.1.3: https://github.com/hackspace-marburg/ffmr-gluon/commit/504a2b1d6bb63b96e0a7e4bf4d0aaca2feae5207

**Comment by rotanid** [comment]
thanks @oleeander for your work.
feel free to update your Pull Request here after the changes have been merged upstream.

**Comment by rotanid** [comment]
the patch has been rejected upstream because it breaks upgrades from existing releases of LEDE.
as Gluon did only have this device as BROKEN, maybe @NeoRaider would be open to this patch in contrast to upstream - otherwise this could be closed.

**Comment by NeoRaider** [comment]
I proposed a solution for the upstream PR, hopefully someone with more free time than me can give it a go (I'd get to it eventually, but probably not before 34C3).

**Comment by mweinelt** [comment]
As we are not going to track these changes downstream and a possible solution¹ was discussed upstream we decided to close this pull request.

1) https://github.com/lede-project/source/pull/1408#issuecomment-337106875

**Comment by rotanid** [comment]
with af9dee336dacbc61e056bce0c0dbf508dd7453a2 in OpenWrt master this devices mac address will work fine with the next OpenWrt major release, integration into Gluon's ath79 target can be done by someone owning such a device as soon as gluon is based on OpenWrt 20.x

**Pull request closed without merging**
