### PR TITLE
Adding support for the Fonera Fon2303a Router

### PR DESCRIPTION
**Pull request by Marlow925**
Adding support for the Fonera Fon2303a Router to Gluon.

A large quantity has turned up for distribution in Freifunk groups and apart from not being able to IBSS mesh, they work perfectly on 802.11s mesh.

### CODE REVIEW

**Comment by rubo77** [comment]
the name of the model ist wrong.

    lua -e 'print(require("platform_info").get_image_name())'

gives the string

    la-fonera-2.0n

if all fonera routers would give that same string, then we would have a problem. because it is usetd for the autoupdater.

see: http://gluon.readthedocs.io/en/v2016.2.2/dev/hardware.html#adding-profiles

**Comment by Marlow925** [comment]
Only this model is named la-fonera-2.0n. Each model of the Foneras has a name and a model number.

The model name .. in this case "la-fonera-2.0n" can be quite confusing. They were named La Fonera (2100a/b/c models), La Fonera+ (2102a), La Fonera 2.0 (2202a), La Fonera 2.0n (2303a - this model), La Fonera Simpl (2305e and 2401a) and La Fonera Mini (can't remember the model).

So the last string was changed to avoid confusion. But if creates a problem with auto-updating the image, then it should of course be adjusted to the string, that the image spits out.

**Comment by rubo77** [comment]
There is missing a

      ifeq ($(BROKEN),)
Around the block

**Comment by NeoRaider** [comment]
The whole *ramips-rt305x* target is marked as BROKEN, no need to add that to individual profiles.

@rubo77 is right about the image name though, it needs to match the model string for the autoupdater to work.

**Comment by eNBeWe** [comment]
Any progress on this PR? @Marlow925 you mentioned something about the MAC-adresses ... do we need to worry about that or can I just patch my gluon tree and build some image for the fonera?

**Comment by Marlow925** [comment]
I've been hung a bit up with work unfortunately. I'll be cleaning the patch up in the next few days and fix the last bits, so we hopefully can get it included in the next released.

**Comment by eNBeWe** [comment]
I built our kiel gluon firmware on 2016.2.3 with this profile (with changed model name). In general it seems to be working, but I am not sure that the router is behaving properly.
When the fonera is up, clients have a hard time completing their handshake.
The status page of the neighboring node shows a fairly "spotty" connection:
mesh-spots

**Comment by rubo77** [comment]
Do you get another result with not-fonera Routers?

**Comment by eNBeWe** [comment]
My node seems to break after some time. The wifi is unusable after this point but the wired client network still works. There are lots of messages stating 
```
Wed Feb 22 22:31:28 2017 kern.err kernel: [ 1910.800000] ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2
Wed Feb 22 22:31:28 2017 kern.err kernel: [ 1910.820000] ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2
Wed Feb 22 22:31:28 2017 kern.err kernel: [ 1910.840000] ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2
Wed Feb 22 22:31:28 2017 kern.err kernel: [ 1910.850000] ieee80211 phy0: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2
```
and after that it is dead.

**Comment by rubo77** [comment]
Vielleicht kann man das fixen indem man das WLAN Modul entlädt und wieder lädt?

**Comment by rubo77** [comment]
Wir haben mal einen Matrix Raum erstellt, um unsere Erfahrungen mit den Foneras zu teilen:

https://riot.im/app/#/room/#freifunk-fonera:matrix.eclabs.de

**Comment by rubo77** [comment]
> The status page of the neighboring node shows a fairly "spotty" connection:

It seems like this is not a problem: it seems to be implemented like that, that the signal has dropouts if there is nothing happening.

Whenever there is traffic, the signal stays stable.

**Comment by rubo77** [comment]
We have a build bash script in our firmware that automatically adds the patches, you can use it for your site.conf too: https://github.com/freifunk-kiel/site-ffki/blob/fonera-lede/make-release.sh

**Comment by rotanid** [comment]
@Marlow925 do you still plan to fix this pull request?

**Comment by Tarnatos** [comment]
Yes he will (regarding to irc).

**Comment by rotanid** [comment]
@Marlow925 @Tarnatos any progress planned to get this done?

**Comment by Marlow925** [comment]
Yes. I've unfortunately been tied down with other commitments in life ... but this will have my outmost priority in the upcoming weeks. Before the end of December anyhow.

**Comment by rotanid** [comment]
is there news about the progress?
if there hasn't been any progress until February, we will close this pull request. you're welcome to reopen it afterwards if you plan to continue working on it.

**Comment by rubo77** [comment]
Just for status info: The Foneras are still working quite unstable even with 2018.1.1.

But we use them for large test setups to enhance the ddhcpd. So we added fonera support in our build process, which automatically executes patches in the [patch directory](https://github.com/freifunk-kiel/site-ffki/tree/nightly/patches) with this script: https://github.com/freifunk-kiel/site-ffki/blob/nightly/.gitlab-ci/patch.sh

**Pull request closed without merging**
