### PR TITLE
docs: add Gluon v2021.1.1 release notes

### PR DESCRIPTION
**Pull request by blocktrron**
Currently soft-blocked by #2284

### CODE REVIEW

**Review by rotanid — APPROVED** [review]

**Comment by rotanid** [comment]
@blocktrron maybe we want to also rebase to 19.07.8 before releasing?

**Comment by blocktrron** [comment]
I'd like to avoid bumping the OpenWrt feed that close to a release. We are not tracking OpenWrt releases for our releases anyways, so I'm not that concerned about it.

**Comment by NeoRaider** [comment]
#2289 (plus the subsequent revert of the PHY index field in `respondd-airtime`) is too late for v2021.1.1 I guess, but I'd like to get that fixed as soon as possible (to avoid having anyone depend on the PHY index for some reason).

The release notes LGTM.

**Comment by rotanid** [comment]
@blocktrron was it intentional to not send a mail about the release like described in the release process?

**Pull request merged**
