### PR TITLE
docs: fix site-example

### PR DESCRIPTION
**Pull request by dg0tm**
* fix missing p - tag
* fix same spaces

### CODE REVIEW

**Comment by dg0tm** [comment]
please don't laugh :)

**Review by AiyionPrime — CHANGES_REQUESTED** [review]
Hey @dg0tm, thanks for your contribution. The changes in your first commit do look good.
For the second I do not see a problem with leaving `respondd`in explicitely, even if just to show it's not a problem to have it in implicitely as well.

Secondly removing it might likely bring trouble, in case communities swapped th regualr status-page to their own, which does not necessarily (even though likely) depend on respondd.

Sorry this took so long, please remove the second commit from your Pr, so we can merge the first one.
If you feel like it was urgent to have the second one as well, you could open another PR, but I'd vote against it for reasons above.

**Comment by dg0tm** [comment]
Yes okay, done...


Am 22.10.22 um 11:49 schrieb Jan-Niklas Burfeind:

**Comment by AiyionPrime** [comment]
@dg0tm looks good. I'll merge this tomorrow morning after fixing the commit message to match the history.

Or you can fix it yourself, if you want to.

**Comment by dg0tm** [comment]
i tried it, but fix it further please..

thanks!

Am 23.10.2022 um 21:46 schrieb Jan-Niklas Burfeind:

**Review by AiyionPrime — APPROVED** [review]
Looks good to me, thanks for your effort!

**Pull request merged**
