### PR TITLE
profiles: add wd mynet n600/n750

### PR DESCRIPTION
**Pull request by RubenKelevra**

### CODE REVIEW

**Comment by RubenKelevra** [comment]
@tcatm anything wrong with this patch? :/

**Comment by NeoRaider** [comment]
As far as I can tell, the image names are wrong (should be `my-net` instead of `mynet`). Please follow the instructions at http://gluon.readthedocs.org/en/latest/dev/hardware.html#adding-profiles to get the correct image names and verify that the names are correct.

**Comment by RubenKelevra** [comment]
@kaechele kannst du mal reinschaun?

**Comment by NeoRaider** [comment]
If you want to get this into Gluon 2015.2, you should fix this soon, as we're getting closer to the release.

**Comment by RubenKelevra** [comment]
Gorgeous guys, thanks! :)

**Pull request closed without merging**
