### PR TITLE
docs: add release notes for Gluon v2016.2.3

### PR DESCRIPTION
**Pull request by NeoRaider**

### CODE REVIEW

**Comment by viisauksena** [comment]
sound bit strange not to make it 2017.1

**Comment by NeoRaider** [comment]
@viisauksena, this is a minor release based on the v2016.2.x branch. v2017.1 will be the next major release.

**Comment by rotanid** [comment]
i'm curious why you remove the support for meraki devices even though somebody created a PR #1004 that fixes the issues - i'm not using any meraki device, but fixing should be preferred.

**Comment by NeoRaider** [comment]
@rotanid The problem is that we don't yet have a way to migrate from a broken Meraki installation to a working one - a sysupgrade will not lead to bootable system because of the changed flash layout.

**Pull request merged**
