### PR TITLE
Config-Mode UI for Interface Role Assignment

### PR DESCRIPTION
**Pull request by lemoer**
First steps towards https://github.com/freifunk-gluon/gluon/issues/2393.

Next steps:
- [x] Allow creation of vlan interfaces.
- [x] Allow deletion of vlan interfaces.
- [ ] Allow expanding /lan, /wan, /single interfaces.
- [ ] Create sections for additional ethernet interfaces in /etc/config/gluon if they do not exist.
- [x] Make *Uplink* and *Client* role mutually exclusive.
- [ ] Test this with a DSA device.
- [ ] Test what happens if we create vlans on swconfig interfaces.
- [ ] Maybe forbidd creating vlans on swconfig interfaces.
- [ ] Readd i18n.

### CODE REVIEW

**Comment by belzebub40k** [comment]
@lemoer I'm working on implementing the bridge isolation feature for mesh links (https://github.com/freifunk-gluon/gluon/pull/2484) and @AiyionPrime suggested that I mention it here as those features are related to the same issue.

**Comment by lemoer** [comment]
Currently this PR looks like this: 
image

**Comment by lemoer** [comment]
Currently the workflow to create a VLAN looks like this:

**Comment by lemoer** [comment]
Roles "Uplink" and "Client" are now mutually exclusive:

**Comment by lemoer** [comment]
I will continue working on this, if #2526 is merged/discussed/decided.

**Comment by lemoer** [comment]
Discussion from the gluon dev meeting 2022-03:

- Maybe build the UI without adding a possibility to expand /lan, /wan and /single interfaces in the first place.
- In the second instance:
    - By default, /lan refers to lan1, lan2, lan3, lan4.
    - If an interface for lan1 is defined, then:
        - lan1 is removed from /lan.
        - So this means that /lan only refers to lan2, lan3, lan4.

**Comment by T-X** [comment]
Looks nice! I'm wondering if there should be some warning + explanation from the UI if the user selects uplink + mesh on an interface. I assume that users are usually not aware why/when this configuration could make their WiFi experience incredibly slow.

**Comment by lemoer** [comment]
In order to simplify things, this is closed in favor of https://github.com/freifunk-gluon/gluon/pull/2688.

**Comment by lemoer** [comment]
> I assume that users are usually not aware why/when this configuration could make their WiFi experience incredibly slow.

@T-X : I do not really understand? This PR is only about the configuration of wired interfaces. How does this influence the WiFi experience?

**Comment by T-X** [comment]
@lemoer it'll influence the WiFi experience when someone uses a standard home router on the uplink side which also has WiFi enabled. Which I guess is a typical scenario? If then using the uplink+mesh roles at the same time then the home wifi router will usually send all the layer 2 broadcast and routing protocol management packets at a slow 1MBit/s wifi bitrate. Depending on the overall mesh network size this could lead to high airtime usage on whatever channel the home router uses.

But anyway, we had the "mesh-on-wan" checkbox before, ready to use in parallel with mesh-vpn. So wouldn't be a "regression", was just wondering if there could be an easy way to give a hint about that potential issue while the UI is updated.

**Pull request closed without merging**
