### PR TITLE
mpc85xx-p1020: add support for Enterasys WS-AP3710i

### PR DESCRIPTION
**Pull request by blocktrron**
The Enterasys / Extreme Networks WS-AP3710i is a ceiling / wall mount PoE powered access point.
It has a dual-core PowerPC processor and dualband WiFi radios.

It can be acquired for cheap (~15 Euros) second hand from IT redistributors.

- [x] must be flashable from vendor firmware
  - [ ] webinterface
  - [ ] tftp
  - [x] other: sysupgrade via initramfs / serial console
- [x] must support upgrade mechanism
  - [x] must have working sysupgrade
    - [x] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [x] must have working autoupdate
    *enterasys-ws-ap3710i*
- [x] reset/wps/phone button must return device into config mode
  - Reset button recessed at the bottom of the device
- [x] primary mac should match address on device label (or packaging) 
  - all mac addresses are printed on the label, matches Radio 1 (5 GHz) wifi mac
(https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
- wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
- wifi (if applicable)
  - [x] association with AP must be possible on all radios
  - [x] association with 802.11s mesh must be working on all radios 
  - [x] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led (_critical, because led definitions are setup on firstboot only_)
    - [x] lit while the device is on
    - [x] should display config mode blink sequence 
  - radio leds
    - [x]  should map to their respective radio
    - [x]  should show activity
  - switchport leds
    - [x]  should map to their respective port (or switch, if only one led present)
    - [x]  should show link state and activity

### CODE REVIEW

**Comment by kpanic23** [comment]
Slightly offtopic, but does the device require 802.3af PoE or will a 24V passive injector suffice? I can't seem to find that information online.

**Comment by blocktrron** [comment]
@kpanic23 The device requires 802.3af (Thankfully)

**Comment by rotanid** [comment]
am i correct, that i always need to flash openwrt first?
my build got me only the sysupgrade image for the device, nothing else...

**Comment by kpanic23** [comment]
Well, yes and no.
You need to boot OpenWRT from RAM (after TFTPing it there), then you can flash Gluon from OpenWRT.

**Comment by blocktrron** [comment]
Correct. The initramfs can be obtained from the latest OpenWrt release build:

https://cdn.openwrt.org/releases/19.07.0/targets/mpc85xx/p1020/openwrt-19.07.0-mpc85xx-p1020-ws-ap3710i-initramfs-kernel.bin

**Comment by rotanid** [comment]
thanks, i knew how to do it, i was just wondering if this is indeed intended.
to which you provided the answer now.

**Pull request merged**
