### PR TITLE
ar8216: support tagged an untagged ports

### PR DESCRIPTION
**Pull request by ogelpre**
This is an patch based on upstream vlan fixes for ar8216 (wdr3600 etc.).

### CODE REVIEW

**Comment by ogelpre** [comment]
This is the Upstream Changeset: https://dev.openwrt.org/changeset/42653

**Comment by NeoRaider** [comment]
Gluon patches in `patches/*` *must* be created by `make update-patches`... I don't think it will even work with a patch formatted like this, `git am` should reject it as there is no commit message in the file.

Just commit your change to the `openwrt` repository in the Gluon directory and run `make update-patches` to create a patch file from your commit.

**Comment by ogelpre** [comment]
uuh, sorry. i'll recreate the patch and pull request.

**Comment by NeoRaider** [comment]
Please squash the two commits to a single one. And the commit message has a typo...

**Comment by NeoRaider** [comment]
I'm a bit confused. OpenWrt r42653 is very old and already included in the Gluon master (which is based on Chaos Calmer). Is this about another chip?

**Comment by NeoRaider** [comment]
No response for months, closing.

**Pull request closed without merging**
