### PR TITLE
ramips-mt76x8: add support for TP-Link RE200 v3

### PR DESCRIPTION
**Pull request by misanthropos**
This commit adds support for dual-band wall-plug wireless range extender
TP-Link RE200 Ver. 3.0.

It can be built with the current "next" branch.

Flashing can be done using the OEM webflash interface using factory-image.

- [x] must be flashable from vendor firmware
  - [x] webinterface
  - [ ] tftp
  - [ ] other: <specify>
- [x] must support upgrade mechanism
  - [x] must have working sysupgrade
    - [x] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [x] must have working autoupdate
    *usually means: gluon profile name must match image name*
- [x] reset/wps/phone button must return device into config mode
- [x] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
- wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
- wifi (if applicable)
  - [x] association with AP must be possible on all radios
  - [x] association with 802.11s mesh must be working on all radios 
  - [x] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led (_critical, because led definitions are setup on firstboot only_)
    - [x] lit while the device is on
    - [x] should display config mode blink sequence 
(https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - radio leds
    - [x] should map to their respective radio
    - [x] should show activity
  - switchport leds
    - [x] should map to their respective port (or switch, if only one led present) 
    - [x] should show link state and activity
- outdoor devices only
  - [ ] added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`

### CODE REVIEW

**Comment by blocktrron** [comment]
`next` is a feature-preview, which is not intended as a target for device integrations. So I'm able to pick this commit there, but it will fall off the branch latest we switch OpenWrt master for the coming release.

**Comment by misanthropos** [comment]
ok - works for me. its just one line to add if modules picks up a fairly recent master owrt.

**Comment by blocktrron** [comment]
Integration has to be re-done then, as we only care for OpenWrt releases, not trunk.

**Comment by misanthropos** [comment]
So I close this PR since this device will be unsupported until the next OpenWRT release?

**Comment by blocktrron** [comment]
Wasn't notified about your comment.

IN short: Yes, this PR can be closed (I'll do so). Either backport the relevant patches to 19.07 and start a discussion over that or wait for Gluon to track the upcoming OpenWrt release.

**Pull request closed without merging**
