### PR TITLE
[Backport v2023.1.x] re-add: ath79 NETGEAR WNDRMAC v2

### PR DESCRIPTION
**Pull request by GoliathLabs**
Backport ath79 NETGEAR WNDRMAC v2 to v2023.1.x with manifest alias.

### CODE REVIEW

**Comment by herbetom** [comment]
please cherry pick from master with the -x flag.

One way of handling the manifest_aliases addition could be to note it as a change in the cherry picked commit:

```
...
(cherry picked from commit dd56c00c61f8b865594de974bbf3a709a718be4e)
[added manifest_aliases for Upgrades from OpenWrt 19.07]
``

**Comment by GoliathLabs** [comment]
Interesting, gh closes PRs on branch reset.

**Comment by GoliathLabs** [comment]
> please cherry pick from master with the -x flag.
> 
> One way of handling the manifest_aliases addition could be to note it as a change in the cherry picked commit:
> 
> ```
> (cherry picked from commit dd56c00c61f8b865594de974bbf3a709a718be4e)
> [added manifest_aliases for Upgrades from OpenWrt 19.07]
> ```

I've now used the -x flag for cherry picking. I've added the manifest addition with the correct commit message, as it appends the manifest alias definition to the original commit.

**Comment by blocktrron** [comment]
>  added manifest_aliases for Upgrades from OpenWrt 19.07 

Change to

>  ath79-generic: add manifest-alias for upgrades from OpenWrt 19.07 

Looks good apart from that.

**Comment by GoliathLabs** [comment]
> > added manifest_aliases for Upgrades from OpenWrt 19.07
> 
> Change to
> 
> > ath79-generic: add manifest-alias for upgrades from OpenWrt 19.07
> 
> Looks good apart from that.

Done

**Pull request merged**
