### PR TITLE
Backports for v2021.1.x 

### PR DESCRIPTION
**Pull request by NeoRaider**
This backports the following PRs to v2021.1.x:

- #2337 
- #2262 
- #2278 
- #2289
- #2304 
- #2330
- #2339
- #2371 
- #2383
- #2394
- #2398
- #2395
- #2392
- #2322

In addition to actual bugfixes, a few additional `gluon-status-page` commits are backported to avoid unnecessary conflicts. The other status page commits make the channel display work again after the backport of freifunk-gluon/packages#251.

### CODE REVIEW

**Comment by lemoer** [comment]
This needs testing. As it only contains setup-mode and status-page changes, testing these features is sufficient.

**Comment by AiyionPrime** [comment]
I forgot to update packages accordingly, will take another round...

**Comment by AiyionPrime** [comment]
@neoraider there was a bug in packages you fixed a while ago, where disabled radios would lead to crashing respondd under $circumstances.

The modules file does not yet have a change in this PR;
not sure whether it would be enough to bump packages or if that would lead to new problems.

It might be cleaner to have packages-backports, a branch which does only reflect bugfixes over there as well.

The issue you fixed was https://github.com/freifunk-gluon/gluon/issues/2327 and you did so in packages on the 25th of october last year.

Without this the routers are obviously still crashing when wifi is disabled.

**Comment by AiyionPrime** [comment]
I thought there was a problem regarding disabled radios, but after rebooting the device everything appears to be fine?

@neoraider maybe you could take a look at packages and decide whether there are backport worthy commits a s well, as modules is still untouched in this PR.

**Comment by AiyionPrime** [comment]
The statuspage looks good for now, but didn't after I initially disabled the wifi interfaces.
The configmode looks good overall, but when I reboot the device, it times out on the last page which should show the vpn-key.

Looking at the map I apparently missed to set the gluon version?
https://hannover.freifunk.net/karte/#/en/map/b44bd6224ebc

> **Firmware version** exp-20220209 / gluon-

Maybe that's related.

**Comment by NeoRaider** [comment]
> The statuspage looks good for now, but didn't after I initially disabled the wifi interfaces.
> 
> [backport.n.ffh.zone](backport.n.ffh.zone)

Do you mean it's working with the PR, or is it still broken with this PR when wifi interfaces are disabled? If so, how are you disabling the interfaces? I don't see any issue with `option disabled '1'` in the `wifi-device` sections.

> 
> The configmode looks good overall, but when I reboot the device, it times out on the last page which should show the vpn-key.
> 
> Looking at the map I apparently missed to set the gluon version? https://hannover.freifunk.net/karte/#/en/map/b44bd6224ebc

I didn't see a timeout, but loading the reboot page did take a bit longer than usual on my WDR3600. Can you check if this happens all the time? Does increasing the sleep before the reboot in `gluon-config-mode-core/luasrc/lib/gluon/config-mode/model/gluon-config-mode/wizard.lua` have an effect? What hardware is this?

**Comment by NeoRaider** [comment]
> > The configmode looks good overall, but when I reboot the device, it times out on the last page which should show the vpn-key.
> > Looking at the map I apparently missed to set the gluon version? https://hannover.freifunk.net/karte/#/en/map/b44bd6224ebc
> 
> I didn't see a timeout, but loading the reboot page did take a bit longer than usual on my WDR3600. Can you check if this happens all the time? Does increasing the sleep before the reboot in `gluon-config-mode-core/luasrc/lib/gluon/config-mode/model/gluon-config-mode/wizard.lua` have an effect? What hardware is this?

@AiyionPrime Can you check if cherry-picking 5166f5e0d97e786bc475fd9f57a9ce5181266383 from the uci-regen branch fixes the issue?

**Comment by AiyionPrime** [comment]
Not sure whether I can reproduce this, but I'm fairly sure I set the name to "backport" its called platzhalter-[...] for now.

**Comment by AiyionPrime** [comment]
I just rebuilt the current uci-regen branch. I think it works better:

The configmode exits cleanly, independent of whether one generated a vpn-key.

The statuspage does not crash, when one disables all wireless interfaces anymore.
It didn't either the last time I tested it a few days ago; there was another problem:
When on restarts the routers wireless using `wifi` the statuspage breaks.
This is not a big problem if a bug at all not one newly introduced.

This PR is working well for me.

I generally have to figure out this gluon-version string though, it's still empty for me...

**Comment by AiyionPrime** [comment]
> What hardware is this?

Cudy WR1000 (ramips)

**Comment by AiyionPrime** [comment]
I just flashed an image, which contains [v2021.1.x-backports](https://github.com/freifunk-gluon/gluon/tree/v2021.1.x-backports) as well as cherry-picked https://github.com/freifunk-gluon/gluon/commit/7b331c2487b6739642abfa9fe5bb1ed3e4c7df04.

Flashing the image works well, I did not see any problems with an initial flash.
Will test upgrading from our current stable, but don't expect problems either.

All hostname-related problems were part of uci-regen.

I think #2394 would be a nice addition for this PR.

**Comment by AiyionPrime** [comment]
Updating from our latest stable based on [v2021.1.1](https://github.com/freifunk-gluon/gluon/tree/0d2f834d317eb49fe2bd0e6ddbba62f5a031fd2b) works fine as well. No hickups during upgrade, no broken statuspage due to disabled wireless interfaces anymore.

**Comment by AiyionPrime** [comment]
Is #2322 a backport candidate as well?

**Comment by NeoRaider** [comment]
> Is #2322 a backport candidate as well?

I guess we could backport it. Ensuring that such big packets can't occur for the default queries is more important though, as respondd is not designed to handle large packets well.

**Comment by NeoRaider** [comment]
I've added a few more cherry-picks to this PR and updated the description accordingly.

**Review by skorpy2009 — APPROVED** [review]
LGTM

**Pull request merged**
