### PR TITLE
Convert site.conf to JSON during build

### PR DESCRIPTION
**Pull request by NeoRaider**
No functional changes so far.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Note: as this fixes an issue with the Lua host installation, at least `make package/lua/host/clean` is necessary to make this build.

**Comment by corny** [comment]
I would prefer to have a site.yml instead of a site.conf.
What is your opinion on that?

**Comment by NeoRaider** [comment]
@corny, yes, sounds like a good idea, but that will have to wait until after the v2016.1 release.

**Comment by corny** [comment]
Ok, great! :+1:

**Pull request merged**
