### PR TITLE
ramips/mt7621: add D-Link Exo AC2600 DIR-882

### PR DESCRIPTION
**Pull request by misanthropos**
- [x] Must be flashable from vendor firmware
  - [x] Web interface
  - [x] TFTP (according to openwrt)

- [x] Must support upgrade mechanism
  - [x] Must have working sysupgrade
    - [x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [x] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [x] Reset/WPS/... button must return device into config mode
- [x] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
- Wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
    - if there are multiple ports but no WAN port:
      - the PoE input should be WAN, all other ports LAN
      - otherwise the first port should be declared as WAN, all other ports LAN
- Wireless network (if applicable)
  - [x] Association with AP must be possible on all radios
  - [x] Association with 802.11s mesh must work on all radios 
  - [x] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [x] Lit while the device is on
    - [x] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [x] Should map to their respective radio
    - [x] Should show activity
  - Switch port LEDs
    - [x] Should map to their respective port (or switch, if only one led present) 
    - [x] Should show link state and activity

- Docs:
  - [x] Added Device to `docs/user/supported_devices.rst`

### CODE REVIEW

**Comment by blocktrron** [comment]
Is this list complete or do the non-marked points not work?

**Comment by misanthropos** [comment]
Its not complete. I will notify you.

**Comment by herbetom** [comment]
Just mark it as draft until it's ready for review: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

Once you've done all testing and it's ready for a review you can mark it as ready for review (the current state). :)

**Comment by misanthropos** [comment]
> Just mark it as draft until it's ready for review: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft
> 
> Once you've done all testing and it's ready for a review you can mark it as ready for review (the current state). :)

Will do. Thank you!

**Comment by misanthropos** [comment]
@blocktrron ready to roll.

**Pull request merged**
