### PR TITLE
gluon-status-page: show site_code & role in node details

### PR DESCRIPTION
**Pull request by achterin**
As suggested by @ambassador86 on irc, this PR adds _site_code_ and _node role_ information to status page.

### CODE REVIEW

**Comment by achterin** [comment]
Testnode: http://[2001:bc8:3f13:ffc2:b24e:26ff:fe90:26a4]/

**Comment by ambassador86** [comment]
Hey @achterin ,
thanks for including this. More interesting than the site code will be the domain code which will differ in chemnitz as soon as we introduce multidomain firmware images. You can find a node running such an image here http://[2001:bc8:3f13:ffc3:7a8a:20ff:fe72:fd83] the respondd data already contains the information.

**Comment by mweinelt** [comment]
And how about the domains pretty name?

**Comment by NeoRaider** [comment]
Please only show the pretty names for everything (site, domain, roles), and hide the labels for unavaible fields.

**Comment by rubo77** [comment]
why is this closed?

**Comment by achterin** [comment]
@rubo77 i closed it because right now i dont want to contribute to this project any longer.

**Pull request closed without merging**
