### PR TITLE
ar71xx: add support for ALFA Network AP120C

### PR DESCRIPTION
**Pull request by h01ger**
Signed-off-by: Holger Levsen <holger@layer-acht.org>

### CODE REVIEW

**Comment by mweinelt** [comment]
Thank your for your pull request. As communicated on IRC we require that you walk through the checklist (https://github.com/freifunk-gluon/gluon/wiki/Device-Integration-checklist) and make sure these things work.

**Comment by mweinelt** [comment]
@h01ger Are you still planning to do the checklist?

**Comment by mweinelt** [comment]
Meanwhile it's 2019, anything new?

**Comment by h01ger** [comment]
On Fri, Jan 18, 2019 at 04:39:37AM -0800, Martin Weinelt wrote:
> Meanwhile it's 2019, anything new?

it will take some time, probabl until summer.

(why) are you bothered by this open merge request?


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by mweinelt** [comment]
Just making sure you didn't just forget, I'm not actually bothered by it. It takes as long as it takes.

**Comment by h01ger** [comment]
On Fri, Jan 18, 2019 at 04:47:10AM -0800, Martin Weinelt wrote:
> Just making sure you didn't just forget, I'm not actually bothered by it. It takes as long as it takes.

ok, thanks.

the device is sitting in its packaging on my window sill, waiting to be
used eventually.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by mweinelt** [comment]
This PR needs to be updated to work with the new lua based target system.

**Comment by mweinelt** [comment]
Hey, this pull has been idle for quite some time and we agreed to close it.

Feel free to ask us to reopen when you're going to continue working on it.

**Pull request closed without merging**
