### PR TITLE
ar71xx-generic: set unifi-ac-lr alias on ac-lite

### LINKED ISSUE #1114: Support for Unifi AP AC LR
The Unifi AP AC Lite as well as the Unifi AP AC Pro got support somewhat a year ago, but the Unifi AP AC LR is still not listed.

Tha hardware looks pretty similar, is support possible? :)

### PR DESCRIPTION
**Pull request by 2tata**
Add alias for Ubiquiti unifi AP AC LR

close #1114

### CODE REVIEW

**Comment by rotanid** [comment]
@2tata have you tested the device with Gluon?

**Comment by 2tata** [comment]
On 02/19/18 08:02, Andreas Ziegler wrote:
> @2tata have you tested the device with Gluon?
> Yes we did that on the last Freifunk Nordwest meeting on 2.2.
I just saw that issue today so I send this MR.

cheers
Tarek

**Comment by 2tata** [comment]
On 02/20/18 00:21, Andreas Ziegler wrote:
> @2tata i just noticed that your commit message is in conflict with the commits content.
> the message says "ac pro" but you actually add it as an alias to ac lite ?
> please think about the right solution twice and force push your change to update your first commit.
> 

I did a misstake in the commit message. I mean AC lite not pro I'll change it now.

**Comment by rotanid** [comment]
thanks!

**Pull request merged**
