### PR TITLE
Patches for next

### PR DESCRIPTION
**Pull request by mkg20001**
- Re-add olsr2 patch:
- Remove mbedtls lib

### CODE REVIEW

**Comment by mkg20001** [comment]
I'm not sure about the mbedtls patch, it was installing a specific version last time I tried building master https://github.com/freifunk-gluon/gluon/commit/8a706b09636877055263ac2c7f4f5f8f92e231ca vs [`836add8` (#2895)](https://github.com/freifunk-gluon/gluon/pull/2895/commits/836add8d16998735e5db20a67b2de9181aa8a183)

The olsr2 patch has been submitted upstream https://github.com/openwrt/routing/pull/973

**Comment by blocktrron** [comment]
@mkg20001 Yes the specific version is renamed on the fly in the build-process, omitting the date is working fine. 

I will take not of this PR, OpenWrt is set to branch soonish. Thanks for fixing this patch, I will apply it once we switch over. Are you fine with this?

**Comment by mkg20001** [comment]
Yes. If there's a chance to get the olsr2 patch merged before branchoff that would also be good, otherwise you can just pull the commit from the pr (I've modified the patch meanwhile to also include the service status command)

Btw for the other patches you can just `git remote add upstream git@github.com:openwrt/REPO.git && git fetch upstream && git rebase -i upstream/master`  in the openwrt/package repo folder and then get the .patch files (note that you'll need to remove all unrelated commits from rebase list)

Git will automatically skip/re-create patches using 3-way merge.

**Comment by mkg20001** [comment]
olsr2 patch is upstreamed and backported https://github.com/openwrt/routing/pull/987#event-9743312298

**Pull request closed without merging**
