### PR TITLE
have respondd work on ff05 in addition to ff02

### PR DESCRIPTION
**Pull request by christf**
This provides one possible solution for #984 

This implies that the hopglass configuration is also changed in the meshes to use ff05:... instead of ff02:..
This is already working with a hopglass instance in FFM

### CODE REVIEW

**Comment by rotanid** [comment]
@christf i guess you meant "hopglass-server", not "hopglass"?
nevertheless, this change will lead to problems depending on the way you plan to introduce it to hopglass-server - it has to work with both configurations because no one will update everything at once (gluon-respondd & hopglass-server) on all nodes.
... forgive me if i don't understand the suggested change and talk nonsense

**Comment by NeoRaider** [comment]
We must only change the meshwide respondd listen address to ff05::..., not the individual mesh interfaces. neighbours-nodeinfo must not be changed.

**Comment by christf** [comment]
if it is not changed, how will the respondd-node on the other node reply if it is subscribed to a different address?

**Comment by jplitza** [comment]
Well, as discussed in #984, respondd has to be taught how to listen to multiple multicast addresses.

**Comment by christf** [comment]
I did not think this was the outcome of the discussion. Hence this pr. 
Not changing neighbours-nodeinfo will result in missing data. 

Am 9. Februar 2017 19:55:51 MEZ schrieb Jan-Philipp Litza <notifications@github.com>:
>Well, as discussed in #984, respondd has to be taught how to listen to
>multiple multicast addresses.

Viele Grüße

Christof
-- 
Diese Nachricht wurde mit K-9 Mail gesendet.

**Comment by NeoRaider** [comment]
neighbours-nodeinfo queries direct neighbours, not mesh-wide. The respondd multicast group on the individual mesh interfaces is supposed to stay ff02::.., so neighbours-nodeinfo must not be changed.

**Comment by christf** [comment]
apparently repsondd did not need to be taught anything and it was just a matter of initialisation.

**Pull request merged**
