### PR TITLE
github: update labeler configuration to v5

### PR DESCRIPTION
**Pull request by blocktrron**
Supersedes #3136 

Configuration file syntax was changed in v5. Change config file accordingly.

### CODE REVIEW

**Comment by neocturne** [comment]
Hmm, is there any way to see a test run of the new config?

**Review by skorpy2009 — APPROVED** [review]

**Comment by blocktrron** [comment]
@neocturne not that i am aware of.

**Comment by grische** [comment]
@neocturne you can test it if you deploy the config on a repo (e.g. a fork) and let it run there.

**Comment by rotanid** [comment]
@neocturne @blocktrron how do we proceed with this PR?

**Pull request merged**
