### PR TITLE
Altitude in meters above the street

### PR DESCRIPTION
**Pull request by rubo77**
To achieve a homogeneous user input in all nodes add details about the reference for the altitude

### CODE REVIEW

**Comment by NeoRaider** [comment]
I don't think we've had a consensus on this solution... and I don't like it at all.

Street level is not well-defined everywhere: What about buildings between streets with different levels? In Lübeck we have a Karstadt building (that actually had a few Freifunk nodes some years ago) that has an "upper ground floor" and a "lower ground floor". Also, small errors in the lat/lon coordinates may cause significant errors in the street level lookup if we were ever to actually do anything with the height value...

**Comment by Adorfer** [comment]
i vote "+" for this PR. 
reason: streetlevel is more likely to be clear, obvious and precise than the current UELN value. 
(most people think if asked about height will think about "Normalnull" as if asked for weight ans responding in pounds.)
Off course a UELN would be gread it given. But due to the fact that it's likely that people will use GNSS-values: Those suffer by design from a DOP in z-axis about 3-10 times the lat/lon dilution. 
meaning: if coordinates are exact by 5m in lat/lon, you will have a height with precision of 40m. 
This makes it possibly totally useless in an area with regular buidings up to 30 metres.

**Comment by rubo77** [comment]
We could add a passus like:

> in case there are different street levels around the house, take the average of the nearest side "

**Comment by tcatm** [comment]
Maybe we could add a note below the input field:

   Altitudes are not yet well defined. Please consult with your community when filling in this information.

**Comment by NeoRaider** [comment]
Hmm, something like that... the word "community" is too Freifunk-specific though.

**Comment by kb-light** [comment]
Maybe one can add some configuration in the site.conf, whether this field should be displayed or not (we actually do not show this field). And a possibility to rename this field in the i18n-files, so every "community" has the ability to rename it.

**Comment by rubo77** [comment]
Maybe we should completely change the **altitude** field into **floor** (Stockwerk, Stockwhich is well defined im most buildings

**Comment by rubo77** [comment]
Rename Altitude to Storey #872

**Comment by jplitza** [comment]
See [my comment in #872](https://github.com/freifunk-gluon/gluon/pull/872#issuecomment-243680860) ⇒ closing.

**Comment by rubo77** [comment]
Ia it possible already to define the Label for altitude in the site/i18n Folder?

**Comment by NeoRaider** [comment]
No, having multiple translations for the same field will yield undefined results. We'd need to remove the current strings and replace them with a placeholder.

**Comment by rubo77** [comment]
https://github.com/freifunk-gluon/gluon/issues/873

**Pull request closed without merging**
