### PR TITLE
batman-adv: update to current openwrt-routing / batman-adv v2019.2

### PR DESCRIPTION
**Pull request by T-X**
This updates the batman-adv OpenWrt package to the current version provided in the master branch of the openwrt-routing packages repository (minus config changes).

The second patch then enables the batman-adv multicast optimizations again.

### CODE REVIEW

**Comment by T-X** [comment]
This partially applies #1357:

* multicast-to-multi-unicast was added in and released with batman-adv v2019.2
* reenables multicast optimizations

What is not added from #1357 yet:

* batman-adv noflood patch
* firewall changes/relaxations

Which in practice means that this should reduce ICMPv6 (and ARP, a few changes in that for batman-adv, too) overhead. But does not allow using multicast for arbitrary addresses yet.

**Comment by rotanid** [comment]
thanks! have you run-tested this? if yes and i don't see a veto in the next days, i will merge it - it's master branch after all.

**Comment by T-X** [comment]
I run-tested it with x86 Gluon via KVM. batman-adv started fine in those three VMs, they were talking to each other and settings were applied.

**Comment by NeoRaider** [comment]
I started a similar update a while ago, with a few more changes. I've just pushed that to the branch wip/update-batadv.

My changes are currently blocked by the implementation of additional netlink interfaces in batadv-legacy, so the same batctl commands are usable for both compat versions.

**Comment by rotanid** [comment]
@NeoRaider your comment doesn't say anything though about whether you prefer to finalize your own patches or are ok with the patches prepared here by TX? please comment on this ;-)

**Comment by T-X** [comment]
@NeoRaider: Awesome! Yes, updating the full openwrt-routing to master is indeed another, good option.

Ideally I would like to have batman-adv v2019.2 in master sooner than later, due to the approaching BattleMesh. So just in case, if someone were to spot any tricky issues in their setup we would be able to investigate and fix it quickly in Paris.

So if openwrt-routing were updated to master in the next few days that would be great. Otherwise, would there be any cons of applying this PR now and then later, without hurry updating to openwrt-routing master?

**Comment by NeoRaider** [comment]
As I don't see batadv-legacy getting the missing netlink calls in the next few days, I propose to go with the small update for now, and update to the routing master later.

**Comment by rotanid** [comment]
@T-X do you need to include the fix from 9e00ecd8e42f3466566b8dd37444e1f02299d05d / #1446 here before we merge this PR ?

**Comment by T-X** [comment]
Changelog v2:
* rebased to include fix from #1446

**Comment by rotanid** [comment]
this change was reverted:
b41ee49aac31c850acdfd6ac1bded99aac99fb31
c1a7733956234417739b05ff269ef8b9f0154a42
reason according to commit message:
Fixes #1756

**Pull request merged**
