### PR TITLE
docs: Suggest peer limit 1 instead of 2

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by tcatm** [comment]
This should also change site-example/site.conf accordingly.

**Comment by rubo77** [comment]
I amended the same in site-example/site.conf, too.

**Comment by do9xe** [comment]
Can you provide a reason, why we should change this? Have the nodes connect to two gateways works fine.

**Comment by rubo77** [comment]
The reason for two uplinks was the worst case, where a gateway crashes often and the peers should have a backup link. I heard, in that case switching to the backup gateway willstill take som 5 seconds.
And if there was no 2nd uplink the node will take about 20 seconds to decide to switch to any other new uplink.

So the gain would be **just some 15 seconds** if a gateway dies (which is not a condition we desire anyway)

The drawback we have every day when all is running fine and all gateways are up and running, is: A lot of more background-Traffic.

So the default suggestion should be `limit 1` and only if you plan to build really instable gateways, that die several times a day, you should set a higher limit

**Comment by tcatm** [comment]
Great! Could you change the commit message in conformance with https://github.com/freifunk-gluon/gluon/blob/master/CONTRIBUTING.md#use-descriptive-commit-messages ?

**Pull request merged**
