### PR TITLE
modules: bump OpenWrt 19.07

### PR DESCRIPTION
**Pull request by blocktrron**
- Update to the latest OpenWrt 19.07 and associated feeds.
- Adjust ipq40xx target name, as otherwise the target won't built anymore.

### CODE REVIEW

**Comment by blocktrron** [comment]
Run-tested: ipq40xx (Fritz!Box 4040)

https://meshviewer.darmstadt.freifunk.net/#!/en/map/989bcbd619e2

**Comment by mweinelt** [comment]
Same for ipq806x?

**Comment by rotanid** [comment]
> Same for ipq806x?
> 
> Also please split up the module bumps and add a shortlog.

+1

**Comment by blocktrron** [comment]
@mweinelt @rotanid 

Updated the commit description. This now only bumps the OpenWrt feed, I will bump the packages seperately.

This change is only necessary for ipq40xx, ipq806x has no generic subtarget.

**Comment by mweinelt** [comment]
> This change is only necessary for ipq40xx, ipq806x has no generic subtarget.

https://github.com/openwrt/openwrt/commit/7407e72399179a185c548c55aaa61a44af497f3f

**Comment by blocktrron** [comment]
You are right, no idea on what i was looking at. Will include this too.

**Comment by belzebub40k** [comment]
`docs/user/supported_devices.rst` need to be adjusted for ipq806x as well.

**Pull request merged**
