### PR TITLE
ar71xx: add support for Archer C7 v4

### LINKED ISSUE #1252: support for TP-Link Archer C7 v4
there's a new revision of the Archer C7 Dual-Band router.
https://wikidevi.com/wiki/TP-LINK_Archer_C7_v4.x
it has the QCA9563 chip instead of the QCA9558 the v2 had.
it has 750 instead of 720 MHz.
LEDE supports it in the master branch for a few weeks now, the backport should be similar in volume to the C25 backport.
https://git.lede-project.org/?p=source.git;a=commit;h=9887afb1afcf387f6892315413e610a6816df463
maybe a country code fix is necessary:
https://github.com/lede-project/source/pull/1490

### PR DESCRIPTION
**Pull request by blocktrron**
This adds support for the TP-Link Archer C7 v4.

Device has no known issue with Gluon. Example Device in the Darmstadt network: https://meshviewer.darmstadt.freifunk.net/#/en/map/50c7bffeba88

closes #1252

### CODE REVIEW

**Comment by rotanid** [comment]
will merge it after someone else also tested this on the device

**Comment by kpanic23** [comment]
At the moment I'm unsure what has to be done to our site config in order to be able to build a current master, so I have just tried backporting your patches to v2017.1.x
(https://github.com/kpanic23/gluon/tree/v2017.1.x)
Will build, try and report :)

**Comment by rotanid** [comment]
@kpanic23 for site.conf/site.mk you may have a look at my changes to these two files:
https://github.com/tecff/site-ffa/commits/master-next/site.conf
https://github.com/tecff/site-ffa/commits/master-next/site.mk
the commit messages should be pretty clear regarding if it is relevant for you and if it is optional. if not, query me on hackint irc gluon channel, not here.

**Comment by kpanic23** [comment]
Hehe, thanks, I'll have a look into it...
Nevertheless, my simple backport seemed to work, and the node owner seems to be happy:
https://map.freifunk-3laendereck.net/#!v:m;n:704f579e7491
So I guess @blocktrron made a good job ;)
Thumbs up!

**Comment by rotanid** [comment]
@blocktrron same question as with the other PR: is there a reason we need to have three separate commits or may we merge them?

**Comment by blocktrron** [comment]
I don't see a problem with squashing them. I've kept them separately due to hardware fixes not yet merged into LEDE/openWRT.

**Comment by rotanid** [comment]
squashed and merged.

**Comment by NeoRaider** [comment]
The LEDE patch numbers conflict with a previous commit. I'll fix this up in a moment...

**Comment by rotanid** [comment]
ah crap, conflict started with d531289deedcbe860c2afb4791d09e8cc6867f4e ...
we only noticed the conflict with the other hardware-PR :(

**Comment by rubo77** [comment]
Will these new models all be backed to the 2017.1.x branch?

**Comment by rotanid** [comment]
@blocktrron just noticed the Archer C7 v2 has specific factory images per country. as you worked with the v4, is this really not necessary for those anymore?

**Comment by NeoRaider** [comment]
@rotanid As the C7 v4 uses the "safeloader" image format, there is an array of supported regions rather than a single region code (see the changes in `tools/firmware-utils/src/tplink-safeloader.c`). Therefore, we can support all regions in a single image.

**Pull request merged**
