### PR TITLE
don't cache index pages which contain meta redirect tags

### LINKED ISSUE #1530: Browser cache, redirections and related issues
When flashing multiple nodes without setting a custom name, they all end up with the same hostname, generated using the first node's host ID. 

I would propose adding "no-cache"-headers to the config mode pages as well as to the status page:

The redirection of different gluon version's status pages differ, if these get cached one can't reach the status page without clearing the browser's cache.

Example: You open the status page using the nextnode address. On Gluon 2018.1 it gets redirected to /cgi-bin/status.
Now, if you try to open a different node's status page running Gluon 2017.1 is not possible, since you get redirected automatically and that path does not exist in older Gluon versions.
The same happens if you downgrade to an older Gluon version.

That redirection should be done using HTTP 303 instead of 301, so it doesn't get cached.

### PR DESCRIPTION
**Pull request by rotanid**
fixes #1530

### CODE REVIEW

**Comment by MyIgel** [comment]
Is there a possibility to set the equivalent headers?

```
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
```

**Comment by mweinelt** [comment]
Much more difficult because we simply want the redirects not to be cached and the webservers just delivers static files.

**Comment by NeoRaider** [comment]
We should be able to add the options mentioned by @MyIgel as meta http-equiv as well.

**Comment by rotanid** [comment]
@NeoRaider i implemented this now.

**Comment by rotanid** [comment]
backported this to v2018.1.x branch

**Pull request merged**
