### PR TITLE
ar71xx-generic: add experimental support for TP-Link CPE210 v2

### PR DESCRIPTION
**Pull request by genofire**
https://forum.freifunk.net/t/tp-link-cpe210-v2-gluon-support/15309/72

https://github.com/FreifunkVogtland/gluon/commit/ffa5a6526f319a43fbe9d0c7721e3c7b87d43dac.patch

@ecsv is it okay?

### CODE REVIEW

**Comment by ecsv** [comment]
No it isn't. First get it upstreamed in OpenWrt. See

* https://github.com/openwrt/openwrt/pull/672
* https://github.com/openwrt/openwrt/pull/642

**Comment by rotanid** [comment]
there's a new upstream PR for this:
https://github.com/openwrt/openwrt/pull/937

**Comment by genofire** [comment]
@rotanid i try to use https://github.com/openwrt/openwrt/pull/937 in this patch
there is still
- [ ] target/linux/ar71xx/base-files/lib/upgrade/platform.sh
to fix in this patch.

**Comment by rotanid** [comment]
@genofire if you want to update your PR here before the upstream one is merged, keep in mind that we won't merge it until it is in upstream

**Comment by achterin** [comment]
@genofire this pr is incomplete and will not compile.
the major issue is the missing backport of the following patch: https://github.com/openwrt/openwrt/commit/b1d57dadb2da0e010e157fd2383523578c9dcc2e
the second issue is that the board definition in _target/linux/ar71xx/image/tp-link.mk_ is wrong and leads to compile errors. "TPLINK_BOARD_ID" needs to be "TPLINK_BOARD_NAME" otherwise the factory image will be rejected by the web-ui. also "tplink-v1-header" needs to be "mktplinkfw-kernel" otherwise you will get compile errors.
this is no attempt to badmouth your work, just a disclaimer for people that might try your pr.

**Comment by genofire** [comment]
@achterin i know :( i just have no time to complete it. I think i will close this PR, sry for it - everybody is free to fork this branch and complete it.

**Comment by achterin** [comment]
@genofire no sweat mate, i completed it and got it working. you can find the code here: https://github.com/achterin/gluon/tree/cpe210v2

**Comment by genofire** [comment]
@achterin  do you create a new PR?

**Comment by achterin** [comment]
@genofire when the time is right for sure. right now the openwrt pull request is still pending, so i have to wait at least till the code gets merged.

**Pull request closed without merging**
