### PR TITLE
add basic danish support in Luci

### PR DESCRIPTION
**Pull request by rubo77**
so danish language files can be added in gluon

### CODE REVIEW

**Comment by rubo77** [comment]
This patch is needed so we can start translating gluon to danish. Without the basic danish support, it is not possible to add daish .po files.

**Comment by mweinelt** [comment]
Isn't this something that is more appropriately tracked upstream? I don't see the need and commitment do maintain danish translations downstream.

https://github.com/openwrt/luci

**Comment by rubo77** [comment]
Some people up here in the North would like to start translate but it is not possible without the Danish enabled in Gluon

**Comment by rubo77** [comment]
And Upstream would be very much work, although we don't need anything of it in gluing.

We need only the base from this patch

**Comment by NeoRaider** [comment]
We're currently removing LuCI from Gluon, obsoleting this patch.

**Pull request closed without merging**
