### PR TITLE
Backport patch for GPIO control

### PR DESCRIPTION
**Pull request by corny**
First prototype, still untested.
- Where is the best place to store the PoE value in the configuration?
- Is it possible to exclude this package in images for non compatible devices?

### CODE REVIEW

**Comment by NeoRaider** [comment]
* The OpenWrt trunk has support for setting GPIO pins, /etc/init.d/gpio_switch is provided by base-files. It reads its settings from /etc/config/system. We should backport the OpenWrt solution instead of building our own.
* The gpio_switch script would always exist when we backport this; but we could choose how to expose this option in the expert mode depending on the hardware. The package would always exist, but just not do anything on incompatible devices.

**Comment by corny** [comment]
Thanks for your hints. I added the patch.
If I find time to create a package for the expert mode, I would prefer to create a second pull request for it.

**Comment by NeoRaider** [comment]
@corny, you should also add r46922.

I also prefer to change the commit metadata when cherry-picking from the OpenWrt trunk (set myself as author using `git commit --amend --reset-author` and remove the git-svn line) to make clear that the original commiter is not responsible for our version of the patch.

**Comment by NeoRaider** [comment]
Ping?

**Comment by Adorfer** [comment]
having a UCI-key for "PPOE-Through" on UBNT-NSM and CPE210 would help a great deal. 
(not doing this via rc.local... this is just a hack)

**Comment by NeoRaider** [comment]
I've committed a rebased version of this PR with my requested changes.

**Comment by corny** [comment]
Sorry, I couldn't find time to get this done.
@Adorfer CPE210 has the same as CPE510.

**Comment by NeoRaider** [comment]
CPE210 and CPE510 aren't differentiated by this code anyways, so the Gluon master now has such a setting. We'll also solve #328 soon.

**Pull request closed without merging**
