### PR TITLE
openwrt: mask nested A-MSDU support for mesh

### PR DESCRIPTION
**Pull request by blocktrron**
This disables A-MSDU support on mesh-links. This restores throughput on mesh-links established between broken (ath10k) and correct (mt76) implementations of mesh A-MSDU.

This patch can be dropped when switching to the next OpenWrt release, as proper fixes have been applied.

Link: https://www.spinics.net/lists/linux-wireless/msg232410.html
Link: https://github.com/openwrt/mt76/issues/450

### Without this patch

```
root@64367-4040:~# iperf3 -c 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378
Connecting to host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378, port 5201
[  5] local 2001:67c:2ed8:100e:eadf:70ff:fe79:bbc1 port 43576 connected to 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  86.1 KBytes   705 Kbits/sec   19   2.36 KBytes       
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    8   2.36 KBytes       
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    8   2.36 KBytes       
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    6   2.36 KBytes       
[  5]   4.00-5.00   sec  41.3 KBytes   338 Kbits/sec   10   2.36 KBytes       
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec   13   1.18 KBytes       
[  5]   6.00-7.00   sec  42.5 KBytes   348 Kbits/sec   14   2.36 KBytes       
[  5]   7.00-8.00   sec  41.3 KBytes   338 Kbits/sec   10   2.36 KBytes       
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec   10   2.36 KBytes       
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec   14   2.36 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   211 KBytes   173 Kbits/sec  112             sender
[  5]   0.00-10.01  sec   189 KBytes   155 Kbits/sec                  receiver

iperf Done.
root@64367-4040:~# iperf3 -c 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 -R
Connecting to host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378, port 5201
Reverse mode, remote host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 is sending
[  5] local 2001:67c:2ed8:100e:eadf:70ff:fe79:bbc1 port 35896 connected to 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  11.1 MBytes  92.5 Mbits/sec                  
[  5]   1.00-2.00   sec  12.9 MBytes   108 Mbits/sec                  
[  5]   2.00-3.00   sec  12.1 MBytes   102 Mbits/sec                  
[  5]   3.00-4.00   sec  11.7 MBytes  97.9 Mbits/sec                  
[  5]   4.00-5.00   sec  12.5 MBytes   105 Mbits/sec                  
[  5]   5.00-6.00   sec  13.1 MBytes   110 Mbits/sec                  
[  5]   6.00-7.00   sec  12.6 MBytes   105 Mbits/sec                  
[  5]   7.00-8.00   sec  12.7 MBytes   106 Mbits/sec                  
[  5]   8.00-9.00   sec  13.1 MBytes   110 Mbits/sec                  
[  5]   9.00-10.00  sec  12.4 MBytes   104 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-13.55  sec   159 MBytes  98.4 Mbits/sec   31             sender
[  5]   0.00-10.00  sec   124 MBytes   104 Mbits/sec                  receiver

iperf Done.
root@64367-4040:~# 

```

### With this patch

```
root@64367-4040:~# iperf3 -c 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378
Connecting to host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378, port 5201
[  5] local 2001:67c:2ed8:100e:eadf:70ff:fe79:bbc1 port 35496 connected to 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  4.28 MBytes  35.9 Mbits/sec    0   70.8 KBytes       
[  5]   1.00-2.00   sec  4.03 MBytes  33.8 Mbits/sec    0   60.2 KBytes       
[  5]   2.00-3.00   sec  4.03 MBytes  33.8 Mbits/sec    0   66.1 KBytes       
[  5]   3.00-4.00   sec  4.03 MBytes  33.8 Mbits/sec    0   75.5 KBytes       
[  5]   4.00-5.00   sec  4.15 MBytes  34.8 Mbits/sec    0   75.5 KBytes       
[  5]   5.00-6.00   sec  4.03 MBytes  33.8 Mbits/sec    0   75.5 KBytes       
[  5]   6.00-7.00   sec  4.03 MBytes  33.8 Mbits/sec    0   75.5 KBytes       
[  5]   7.00-8.00   sec  4.15 MBytes  34.8 Mbits/sec    0   81.4 KBytes       
[  5]   8.00-9.00   sec  4.03 MBytes  33.8 Mbits/sec    0   86.1 KBytes       
[  5]   9.00-10.00  sec  4.15 MBytes  34.8 Mbits/sec    0   97.9 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  40.9 MBytes  34.3 Mbits/sec    0             sender
[  5]   0.00-10.01  sec  40.6 MBytes  34.1 Mbits/sec                  receiver

iperf Done.
root@64367-4040:~# iperf3 -c 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 -R
Connecting to host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378, port 5201
Reverse mode, remote host 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 is sending
[  5] local 2001:67c:2ed8:100e:eadf:70ff:fe79:bbc1 port 40480 connected to 2001:67c:2ed8:100e:aa63:7dff:fe2e:9378 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  5.91 MBytes  49.5 Mbits/sec                  
[  5]   1.00-2.00   sec  5.66 MBytes  47.4 Mbits/sec                  
[  5]   2.00-3.00   sec  5.56 MBytes  46.6 Mbits/sec                  
[  5]   3.00-4.00   sec  5.39 MBytes  45.2 Mbits/sec                  
[  5]   4.00-5.00   sec  5.84 MBytes  49.0 Mbits/sec                  
[  5]   5.00-6.00   sec  5.28 MBytes  44.3 Mbits/sec                  
[  5]   6.00-7.00   sec  5.28 MBytes  44.3 Mbits/sec                  
[  5]   7.00-8.00   sec  6.01 MBytes  50.4 Mbits/sec                  
[  5]   8.00-9.00   sec  4.70 MBytes  39.4 Mbits/sec                  
[  5]   9.00-10.00  sec  4.50 MBytes  37.8 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.05  sec  54.7 MBytes  45.7 Mbits/sec    4             sender
[  5]   0.00-10.00  sec  54.1 MBytes  45.4 Mbits/sec                  receiver

iperf Done.
root@64367-4040:~# 
```

### CODE REVIEW

**Comment by blocktrron** [comment]
@Djfe @AiyionPrime Can you check if this fixes the issues you've reported?

**Comment by Djfe** [comment]
will do 👍

**Comment by blocktrron** [comment]
I'm not sure if this should be applied upstream. As one can see, the RX performance naturally halves, thus this would result in a 50% reduction in performance for ath10k-only mesh setups.

For Gluon, I think this is sufficient as we aim to prioritize interoperability over performance. As the issue will eventually be fixed by switching to a newer OpenWrt base, i cam to the conclusion the patch being the best compromise in this case.

**Comment by Djfe** [comment]
I was fearing as much :/
Can't we limit this to mt76 somehow? Or does the change have to be run on the encoding site (QCA) as well?
The commit message reads itself in a way that implies it only affects the decoding (receiving) side. (it's enough to stop indicating support)

**Comment by blocktrron** [comment]
Please read the patch from nbd. It implements the frame-length adaption on RX. This patch circumvents the RX path mismatch by avoiding entering a A-MSDU session.

> Can't we limit this to mt76 somehow?

Yes. This is considerable more work, but feel free to submit a PR.

**Comment by Djfe** [comment]
ok so I just did some testing using speedtest.net.
I originally planed on using iperf3 between the nodes but I couldn't get it to work.
Tests where done between QCA9888 and mt7905 (tp-link archer C6 v2, d-link dap-x1860). My notebook was connected to the client ethernet port of the mt7905.
The bug this is trying to fix definitely appears regardless of whether the qca chip is run by ath10k or ath10k-ct.
Though you can make out different behavior in how transfer speed accelerates (with this bug).
The bug didn't always happen (immediately) but toggling wifi or rebooting always worked out great in retriggering the bug. I checked this first in order to know how I could trigger it successfully.
Both devices are running a master-based image.

I sysupgraded the mt7905 node to the patched version and the workaround fixes the issue successfully.
I tried several constellations and conditions that usually triggered the bug but it didn't occur.
Eventually I also switched places and connected my notebook to the qca side instead and let the mt7905 handle the uplink to our supernode instead.
No issues there either.

I plan on repeating these tests with a Cudy X6 v2 (mt7905) and a Linksys MR8300 (ipq40xx).
And also between two mt7905 devices to rule out regressions. This still leaves out quite a few mesh combos with qca988x, qca9887 and mt7915 etc. instead of the chips tested here. But I'm confident we don't need to test all of them since it's fairly clear why this workaround improved meshing. A regressions feels unlikely.
If you really want to roll out this patch for ath10k as well, then we should test ath10k only setups for regressions as well (apart from speed).

Conclusion:
It's nice to know that this workaround improved meshing between qca and mtk quite a lot.
Since the real fix might not receive a backport this might be our only chance at somehow patching this for openwrt-22. (at least to me it feels like this kind of patch won't be backported, I could be wrong)

**Comment by Djfe** [comment]
I feel like this should be merged now even if it's just for Gluon 23.01 (Gluon 23.02 will get the actual fix from upstream)
Are we waiting for feedback from others still?
@AiyionPrime maybe

**Comment by Djfe** [comment]
@sdirek run snapshot or openwrt-23 release candidate on both of them.
It has been fixed in openwrt main for months.
The issue appeared because you were running openwrt-22 on the xiaomi still :)

**Pull request merged**
