### PR TITLE
ath79-nand: (re)add support for glinet_gl-ar300m

### PR DESCRIPTION
**Pull request by AiyionPrime**
@rotanid received the image for testing.

- [ ] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [ ] Other: <specify>
- [X] Must support upgrade mechanism
  - [X] Must have working sysupgrade
    - [X] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [ ] Must have working autoupdate
        *Usually means: Gluon profile name must match image name*
- [X] Reset/WPS/... button must return device into config mode
- [X] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
- Wired network
  - [X] should support all network ports on the device
  - [X] must have correct port assignment (WAN/LAN)
    - On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
      The PoE input should be the WAN port in this case.
- Wireless network (if applicable)
  - [X] Association with AP must be possible on all radios
  - [X] Association with 802.11s mesh must work on all radios 
  - [X] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/sys LED
    - [X] Lit while the device is on
    - [X] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [X] Should map to their respective radio
    - [X] Should show activity
  - Switch port LEDs
    - [X] Should map to their respective port (or switch, if only one led present) 
    - [X] Should show link state and activity
- Outdoor devices only:
  - ~~Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~

### CODE REVIEW

**Comment by rotanid** [comment]
flashed Freifunk Hannover ar71xx image vH21, sysupgrade to the test-image based on this PR, tested and checked the list in this PR.
can't test autoupdate, won't test flash from factory.

seems to be merge-ready

**Comment by AiyionPrime** [comment]
The image as part of the generic subtarget in ar71xx.
In order for it to become a "real" nand subtarget its necessary to have this sort of intermediate nor image. There is a similar device that awaits this migration as well, if I'm not mistaken:

> Changed subtarget in between, similar change in
commit https://github.com/freifunk-gluon/gluon/commit/bed66fa24856057eadd252eef8144df1c894112f ("ath79: move GL.iNet GL-AR750S to NAND subtarget")

**Comment by NeoRaider** [comment]
> The image as part of the generic subtarget in ar71xx. In order for it to become a "real" nand subtarget its necessary to have this sort of intermediate nor image. There is a similar device that awaits this migration as well, if I'm not mistaken:
> 
> > Changed subtarget in between, similar change in
> > commit [bed66fa](https://github.com/freifunk-gluon/gluon/commit/bed66fa24856057eadd252eef8144df1c894112f) ("ath79: move GL.iNet GL-AR750S to NAND subtarget")

@AiyionPrime  It is also in the nand subtarget to include the NAND drivers in the kernel - I think this may even make sense when the NAND is not used for the firmware image at all.

Do you know if migration to the NAND image will actually be necessary at some point, or will the NOR image just continue to work? Do upgrades from NOR to NAND preserve configuration?

**Comment by AiyionPrime** [comment]
@NeoRaider I have not seen movement regarding nor-nand migration of that device, yet.

Looking at growing image sizes, not using the 128MB NAND but only the 16MB NOR would be a waste.

From what I read, updates where definitely not possible from ath79 prior November 15th, 2019.
Upgrading would work most of the time but might result in booting the old system [1](https://openwrt.org/toh/gl.inet/gl-ar300m). Under which circumstances it does, I do not know yet.
Neither whether the config is kept while migrating from NOR to NAND.

That is not yet the scope of this PR; this does 'only' account for the ath79-migration.
I thought one would be enough per PR :D
I could extend the PR and build the NAND-image too, if @rotanid was interested in testing that as well.


As there are variants of the gl-ar300m, that do not come with NAND-storage, but only NOR, it's unlikely the NOR image will be gone soon for this particular device.

**Comment by NeoRaider** [comment]
As long as Gluon fits in the NOR nicely, I'd like to avoid migration to NAND, as NAND is less reliable.

**Comment by AiyionPrime** [comment]
fine with me.

**Pull request merged**
