### PR TITLE
ramips-mt76x8: add support for GL.iNet VIXMINI

### PR DESCRIPTION
**Pull request by blocktrron**
GL.iNet VIXMINI is a 300M router based on MT7628 with 8M Flash and 64M RAM. Currently, it can only be bought from china for 20$ either on [AliExpress](https://de.aliexpress.com/wholesale?SearchText=Vixmini) or [GL.iNet shop](https://store.gl-inet.com/collections/all-wifi-devices/products/vixmini-mini-travel-router).

- [x] must be flashable from vendor firmware
  - [x] webinterface
  - [x] other: bootloader httpd
- [x] must support upgrade mechanism
  - [x] must have working sysupgrade
    - [x] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [x] must have working autoupdate
    *usually means: gluon profile name must match image name*
     > root@64367-vixmini:~# lua -e 'print(require("platform_info").get_image_name())'
     > gl.inet-vixmini
- wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
- wifi (if applicable)
  - [x] association with AP must be possible on all radios
  - [x] association with 802.11s mesh must be working on all radios 
  - [x] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led (_critical, because led definitions are setup on firstboot only_)
    - [x] lit while the device is on
    - [x] should display config mode blink sequence 
(https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - radio leds
    - [x] should map to their respective radio
    - [x] should show activity
- [x] reset/wps button must return device into config mode
- [x] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)

### CODE REVIEW

**Comment by rotanid** [comment]
hm, this backport patch isn't really justified as would be necessary per our device integration guidelines as it is neither a new version of a popular device nor is it widely available...
i won't stop another committer from merging it, though.

**Comment by blocktrron** [comment]
yup, this is currently an issue. I have hopes this changes as GL.iNet does not even have a product page for the device (yet), only their store listing (and some half-baked docs). GL.iNet offers their other routers on Amazon DE, so the VIXMINI hopefully starts being sold there too.

**Comment by mweinelt** [comment]
This PR needs to be updated to work with the new lua based target system.

**Comment by rotanid** [comment]
> yup, this is currently an issue. I have hopes this changes as GL.iNet does not even have a product page for the device (yet), only their store listing (and some half-baked docs). GL.iNet offers their other routers on Amazon DE, so the VIXMINI hopefully starts being sold there too.

it has a product page now and is available on amazon US, but i haven't found a german source, yet.

**Comment by blocktrron** [comment]
Fun stuff: It now seems they are calling it "Microuter": https://store.gl-inet.com/collections/all-wifi-devices/products/vixmini-mini-travel-router

**Comment by bobcanthelpyou** [comment]
@blocktrron did the router disappeared from the shop, your last link -> "404 Not Found"

Is https://www.gl-inet.com/products/vixmini/ the correct product page of that device?

**Comment by blocktrron** [comment]
Yes, this is the real Product Page. The microuter-n300 page moved here: https://store.gl-inet.com/collections/mini-smart-router/products/microuter-n300-mini-travel-router

The case looks identical except for the color, however it has double the RAM / flash compared with the VIXMINI (if the shop page is correct).

**Comment by mweinelt** [comment]
Please drop the patches and rebase against master.

**Comment by blocktrron** [comment]
Updated PR, will redo the checklist this evening and report back.

**Comment by blocktrron** [comment]
Updated and everything remains working as expected.

**Comment by mweinelt** [comment]
Please add the VIXMINI to the list of support devices.

**Pull request merged**
