### PR TITLE
ar71xx: add support for Archer C7 v5

### PR DESCRIPTION
**Pull request by mweinelt**
@rotanid testing
@blocktrron author

me? I'm just adding this pr so people can find the change and not start form scratch.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Does "testing" mean that testing is done and this is ready for merging?

**Comment by blocktrron** [comment]
@NeoRaider definitely no as switch LEDs still need to be fixed upstream https://github.com/openwrt/openwrt/pull/1411

**Comment by mweinelt** [comment]
Please also update `docs/index.rst`.

**Comment by blocktrron** [comment]
updated

**Comment by rotanid** [comment]
- [ ] must be flashable from vendor firmware
  - [ ] webinterface
  - [ ] tftp
  - [ ] other: <specify>
- [ ] must support upgrade mechanism
  - [ ] must have working sysupgrade
    - [ ] must keep/forget configuration (if applicable)
      *think `sysupgrade [-n]` or `firstboot`*
  - [ ] must have working autoupdate
    *usually means: gluon profile name must match image name*
- wired network
  - [ ] should support all network ports on the device
  - [ ] must have correct port assignment (WAN/LAN)
- wifi (if applicable)
  - [ ] association with AP must be possible on all radios
  - [ ] association with 802.11s mesh must be working on all radios 
  - [ ] ap/mesh mode must work in parallel on all radios
- led mapping
  - power/sys led
    - [ ] lit while the device is on
    - [ ] should display config mode blink sequence 
(https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - radio leds
    - [ ] should map to their respective radio
    - [ ] should show activity
  - switchport leds
    - [ ] should map to their respective port (or switch, if only one led present) 
    - [ ] should show link state and activity
- [ ] reset/wps button must return device into config mode
- [ ] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)

**Comment by daseinsfreude** [comment]
@rotanid: Your testing looks very professional. I am not as professional as you are but I would also like to contribute :-)
I tested the experimental version from Freifunk 3 Ländereck. Thanks to David !
```
https://ftp.ff3l.net/master/experimental/factory/gluon-ff3l-gd00acd4+
sda2e928~20181010-tp-link-archer-c7-v5.bin
```

- flashable via tftp
- mesh connection to another Freifunk router via 2,5 Ghz
- WIFI LED 2,5 & 5 Ghz not working but the Internet connection works perfectly


Kind regards from Switzerland :-)

**Comment by rotanid** [comment]
@daseinsfreude thanks for your help. the checklist i use was developed together with others as a template for this kind of testing. it's not mine.
thanks for your additional tests. maybe the build by @kpanic23 doesn't include the LED patch properly...

meanwhile, @brainpower also helped testing and therefore everything is tested now.

the things which don't work:

- flashing via the vendor Webinterface
- restoring the vendor/stock/original firmware (but who would want that? even if you dont want gluon, OpenWrt is better than the original firmware...)

**Pull request merged**
