### PR TITLE
ath79-nand: (re)add WNDR4300v1

### PR DESCRIPTION
**Pull request by AiyionPrime**
> Gone due to
> commit 45c84a1 ("ar71xx: drop target")

~~"alexp" from hackint#ffda intends to test this device.~~

- Must be flashable from vendor firmware
  - ~~Web interface~~
  - ~~TFTP~~
  - Other: https://github.com/jclehner/nmrpflash
- [x] Must support upgrade mechanism
  - [x] Must have working sysupgrade
    - [x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [x] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [x] Reset/WPS/... button must return device into config mode
- [x] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
    - On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
      The PoE input should be the WAN port in this case.
- Wireless network (if applicable)
  - [x] Association with AP must be possible on all radios
  - [x] Association with 802.11s mesh must work on all radios 
  - [x] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [x] Lit while the device is on
    - [x] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [x] Should map to their respective radio
    - [x] Should show activity
  - Switch port LEDs
    - [x] Should map to their respective port (or switch, if only one led present) 
    - [x] Should show link state and activity
- Outdoor devices only:
  - ~~Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~

### CODE REVIEW

**Comment by AiyionPrime** [comment]
A misunderstanding, he thought we'd need a TP-Link device with 4300 in its name.

**Comment by AiyionPrime** [comment]
The kernel partition size was increased in https://github.com/openwrt/openwrt/commit/0d28e5d6440d2a37841a207f943e6e5a23172883 which broke ar71xx compatibility.

I've got the device laying here, I could add it as a new device for the eight users of similar devices. Any recommendations on how to proceed?

**Comment by AiyionPrime** [comment]
I'd suggest we add it as device again, and mark the missing migration in the releasenotes.
OpenWrt removed `SUPPORTED_DEVICES` entry, so that should be fine.
Any objections?

**Comment by blocktrron** [comment]
@AiyionPrime No, we don't add the device without completing the integration verification please.

**Comment by AiyionPrime** [comment]
I did not intend to, sorry.
Wanted to express that I'll intend to leave the code as is, not that I'll be merging this untested in a moment.

**Comment by blocktrron** [comment]
AH, I've misread that (And also the checkboxes were not there for me with your last comment?).

Missing migration should be okay. There is nothing reasonable to do for us anyways.

**Pull request merged**
