### PR TITLE
ramips-mt7621: add ASUS RT-AX53U

### PR DESCRIPTION
**Pull request by maurerle**
Add support for ASUS RT-AX53U

- [x] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [x] Other:
    - ssh > mtd-write factory image to Kernel-partition
      [Wiki instructions](https://openwrt.org/toh/asus/rt-ax53u#installation_with_mtd-write)
    - tftp via serial (requires opening the case)
      [Wiki instructions](https://openwrt.org/toh/asus/rt-ax53u#installation_with_tftp)
    - Asus Firmware Restoration Tool on Windows
      Flash OpenWrt Kernel/initramfs first, then sysupgrade to Gluon
      [Asus Instructions](https://www.asus.com/support/FAQ/1000814/)
      [Download Firmware Restoration Tool](https://dlcdnets.asus.com/pub/ASUS/wireless/GT-AX6000/Rescue_2103.zip)
- [x] Must support upgrade mechanism
  - [x] Must have working sysupgrade
    - [x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [x] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
        `asus-rt-ax53u`
- [x] Reset/WPS/... button must return device into config mode
- [x] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
      Device has two MACs:
  - 50:eb:f6:83:2c:14 (2.4GHz and LAN and WAN) < primary and printed on the label
  - 50:eb:f6:83:2c:18 (5GHz)    
  - ~~When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.~~
- Wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
    - ~~if there are multiple ports but no WAN port~~:
      - ~~the PoE input should be WAN, all other ports LAN~~
      - ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- Wireless network (if applicable)
  - [x] Association with AP must be possible on all radios
  - [x] Association with 802.11s mesh must work on all radios 
  - [x] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [x] Lit while the device is on
    - [x] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [x] Should map to their respective radio
    - [x] Should show activity
  - Switch port LEDs
    - [x] Should map to their respective port (or switch, if only one led present) 
    - [x] Should show link state and activity
- Outdoor devices only:
  - [ ] ~~Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
- Cellular devices only:
  - [ ] ~~Added board name to `is_cellular_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
  - [ ] ~~Added board name with modem setup function `setup_ncm_qmi` to `package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular`~~
- Docs:
  - [x] Added Device to `docs/user/supported_devices.rst`
 
The device is running Gluon and works ~~but the LEDs have some issues~~

Performance:
110 Download, 38 Upload via Wireguard on a 250/40 VDSL2 connection
VPN performance improved noticeably since I created this PR (typically it reached around 80-100mbit/s Download before)

### CODE REVIEW

**Comment by Djfe** [comment]
I own the device for which @maurerle created this PR

Power LED, Wifi LEDs and USB LED aren't working, yet.
There is no Sys LED and nothing blinks to indicate config mode.

WAN/LAN LEDs work fine and blink with activity (one blue led per port), there are no link/activity led's on the lan ports themselves though.
If no cable is connected to the box, then all LEDs are turned off.

There exist PRs to add LED support but they weren't merged, yet.
Wifi LEDs have to be controlled by the driver (mt76), which appears to be implemented but not in snapshots either.
https://github.com/openwrt/openwrt/pull/10400
https://github.com/openwrt/openwrt/issues/11068

Apart from that the device works fine though.
Throughput with Wireguard over my VDSL connection (↓ 256,5 Mbit/s ↑ 45,6 Mbit/s) on Wifi with my Pixel 7 Pro is up to 97/38.
LAN is slower for some reason:
59/29

For 66€ this will be a great entry device. (it has 2 antennas per frequency and supports up to 80MHz and WiFi6)

I still have to test meshing with other 802.11s nodes.
Apart from that and the LEDs everything else is working.
Flashing can be cumbersome (SSH) but there is a recovery tool from ASUS and alternatively you can tell the bootloader via serial to flash from tftp.

**Comment by Djfe** [comment]
ok meshing works as well :)
As far as I understand it, we did everything that needs to be done.
If you want some of the existing PR patches for LED Support, then pls tell us. If not, then this PR is probably ready to be merged.

**Comment by lukjod** [comment]
does it mean also wifi leds will work inn snapshot?

**Comment by Djfe** [comment]
no. I tested the latest openwrt release and snapshot builds. WiFi leds, power LED and and USB LED aren't working, yet.
Support is being worked on/on the way but there is no actual ETA.

**Comment by AiyionPrime** [comment]
LED support is coming along nicely it seems.
https://github.com/openwrt/openwrt/issues/11068#issuecomment-1358143040

@Djfe maybe you could join their discussion and offer to test their work.
Things usually get merged faster, when they're tested by several parties.

**Comment by AiyionPrime** [comment]
Backport made it through the mailinglist:

https://patchwork.ozlabs.org/project/openwrt/patch/20230105142924.11490-1-git@aiyionpri.me/

**Comment by Djfe** [comment]
you mistook this for the o2 issue. this is about the Asus router.

Status update:
leds were implemented by now. What's kinda missing: wifi led support.
They could've patched it fully in openwrt by setting a build flag, But they prefer the upstream solution to set the flag for all devices with an MT7915 soc in the MT76 driver.

Once this is implemented, then we are pretty much done.
https://github.com/openwrt/mt76/pull/725

**Comment by Djfe** [comment]
quick question about ALT0 devices:
they have the exact same build but an additional name.
Does this PR need to be adjusted for this?
The Asus RT-AX1800U is the same device as this one. (both stock firmware files have the same hash value)

**Comment by Djfe** [comment]
Ok, so the WiFi driver just received an update and LEDs should be working in master now.
https://github.com/openwrt/openwrt/commit/521efb62ebb55dcc67dc618757aa2e3ccbdf3774

I'll check again later and me and @maurerle will revise this patch, so it can merged once it hits the next release branch
There's also this PR that I help on getting into OpenWRT, it's about merging two partitions into one for more available flash space and about nmbm support:
https://github.com/openwrt/openwrt/pull/11806
I'll have to address the latest comments though (I didn't have time for it this week). Maybe we can still get it into next release, we will see.

**Comment by maurerle** [comment]
Waiting on upstream backport: https://github.com/openwrt/mt76/pull/767

**Comment by maurerle** [comment]
As we moved to the upcoming openwrt 23.05 branch, we can now add support for this device.
Tests have happened and the `nmbm` PR is also part of v23.05-rc3.

Maybe a final test with a current master build would be quite good to confirm everything is now working as expected.

**Comment by blocktrron** [comment]
Yes, please re-test with the latest base and ping me.

**Comment by Djfe** [comment]
maybe over the weekend :)
same goes for my Linksys PR

**Comment by maurerle** [comment]
@blocktrron this was retested and is ready to be merged.
Thanks a lot @Djfe

**Comment by Djfe** [comment]
not yet, you still need to update the commit so it creates a factory image, please :)

**Review by Djfe — APPROVED** [review]

**Comment by Djfe** [comment]
jay, danke!

**Pull request merged**
