### PR TITLE
ath79: add GLinet and AVM-devices

### PR DESCRIPTION
**Pull request by SvenRoederer**
This adds the following devices, which are already present in ar71xx:

* AVM Fritz!BOX 4020, WLAN-Repeater 300e
* GLinet AR150, GLinet AR300m (lite)
  * GLinet AR300m gets disabled, as done in OpenWRT

### CODE REVIEW

**Comment by mweinelt** [comment]
Thanks for your contribution, but I'm not sure we are ready yet to accept devices in ath79 which are also in ar71xx.

- One issue will be colliding filenames when both targets are being built, so we will likely need to disable devices in ar71xx as soon as they're added in ath79.
- Another issue is the question how migration between ar71xx and ath79 will work. We've discussed this a bit in #1570.
- And third issue is … we're going to need device checklists (https://github.com/freifunk-gluon/gluon/wiki/Device-Integration-checklist) for every device that we accept/migrate into ath79.

**Comment by SvenRoederer** [comment]
Esp. the issue with having the device in both targets I also had in mind. So this PR might be a good place to discuss on this.
As I had this commits prepared already, I published them to not get them lost.

**Comment by blocktrron** [comment]
@SvenRoederer Until we have a migration strategy, ath79 and ar71xx is XOR in terms of device support. Also the checklist is missing as @mweinelt pointed out.

Regarding ath79 migration, there is already a tracking issue present in #1570 . So I'm in favor of closing this PR and discuss it there. Any objections against this?

**Comment by SvenRoederer** [comment]
I'm fine with this.

**Pull request closed without merging**
