### PR TITLE
make sure folder paths used in gluon buildroot are absolute (fixes issue #1264)

### LINKED ISSUE #1264: build dies when GLUON_SITE is a relative path
#$ make GLUON_TARGET=ar71xx-generic DEVICES=tp-link-archer-c25-v1 -j 1 BROKEN=1 GLUON_SITEDIR=../site-ffkbuk/ V=s

```
make[4]: Entering directory '/raider/foo/gluon/gluon2017.1.4/package/gluon-site'
GLUON_SITEDIR='../site-ffkbuk/' lua -e 'print(require("cjson").encode(assert(dofile("../../scripts/site_config.lua"))))' > /raider/foo/gluon/gluon2017.1.4/lede/build_dir/target-mips_24kc_musl-1.1.16/gluon-site/site.json
lua: ../../scripts/site_config.lua:9: ../../scripts/site_config.lua:5: attempt to index a nil value
stack traceback:
        [C]: ?
        [C]: in function 'load'
        ../../scripts/site_config.lua:9: in main chunk
        [C]: in function 'dofile'
        (command line):1: in main chunk
        [C]: ?
stack traceback:
        [C]: in function 'assert'
        ../../scripts/site_config.lua:9: in main chunk
        [C]: in function 'dofile'
        (command line):1: in main chunk
        [C]: ?
Makefile:60: recipe for target '/path/gluon2017.1.4/lede/build_dir/target-mips_24kc_musl-1.1.16/gluon-site/.built' failed
```

the probably easiest fix would be to assure that GLUON_SITEDIR is absolute by modifying it in the gluon buildroot Makefile. stackoverflow suggests realpath if gluon is Gnu make specific
  https://stackoverflow.com/questions/5969129/makefile-expand-relative-prefix-path

..ede

### PR DESCRIPTION
**Pull request by edeso**
make sure folder paths used in gluon buildroot are absolute, so they can be reused in subfolder package makefiles w/o headaches, fixes #1264 

uses a call function to the shell realpath because
- gnu make realpath function returns "" on non existing folders (some folders to test are created during the build only)
- gnu make abspath function chokes on spaces in path
- shell realpath accepts a parameter to ignore non-existing path components

please be patient. this is my first github pull request with next to no git experience and gnu make is a horrible way to code (not fluent in it either)

..thx ede

### CODE REVIEW

**Comment by NeoRaider** [comment]
Hmm, I'm not sure if the realpath command is portable on *BSD / MacOS; while I wouldn't call these systems "supported" by Gluon, we should not deliberately break them.

How about using Make's `abspath` after checking the path is a single word? Spaces aren't allowed in any paths used in the Gluon build anyways, because Make generally handles them poorly.

**Comment by edeso** [comment]
On 11/28/2017 22:12, Matthias Schiffer wrote:
> Hmm, I'm not sure if the realpath command is portable on *BSD / MacOS; while I wouldn't call these systems "supported" by Gluon, we should not deliberately break them.
> 
> How about using Make's |abspath| after checking the path is a single word? Spaces aren't allowed in any paths used in the Gluon build anyways, because Make generally handles them poorly.
> 

thanks for the quick reply. understand your point and wasn't aware that gluon buildroot is supposed to be run on non-linux boxes.

i see where you are going, how about 
- a space check issuing an error ala https://stackoverflow.com/questions/10230953/how-to-check-whether-a-variable-contains-spaces-in-a-makefile
- dumbed down gnu make only make absolute path version, that checks for the first char being a slash and if it's not adds the current dir in front
?

..ede

**Comment by NeoRaider** [comment]
Checking for spaces and aborting with an error seems okay to me.

**Comment by edeso** [comment]
Neo,

the latetst version should do the trick. ..ede

**Comment by edeso** [comment]
@NeoRaider any reason not to merge this PR? ..ede

**Comment by NeoRaider** [comment]
Thanks, squashed and merged with a few changes. Sorry for the delay, I've had very busy last 2 weeks.

**Comment by edeso** [comment]
On 12/25/2017 18:01, Matthias Schiffer wrote:
> Thanks, squashed and merged with a few changes. 

unfortunately the debug out was removed by you. i quite liked it as it pretty much showed all important paths when V=s was defined and these might be important to find out why buildroot is not working as expected.

>Sorry for the delay, I've had very busy last 2 weeks.

sh** happens, thanks for maintaining this beast!.. ede

**Pull request closed without merging**
