### PR TITLE
Added: Dependabot.yml config

### PR DESCRIPTION
**Pull request by GoliathLabs**
Hello,
I have added a dependabot.yml configuration file. Dependabot will check for updates of the gh-actions used as well as the python requirements in the docs folder on a monthly basis.

### CODE REVIEW

**Comment by blocktrron** [comment]
I see Dependabot as a tool to be aware of keeping dependencies up to date for security / bug fixing reasons.

For the GitHub actions, I do not see such a need at all, given we are not doing funky stuff with it.

The documentation might be a bigger headache to keep up to date, given we rarely touch the Sphinx stack at all.

Have you tested, whether a simple version bump still builds the other CI steps?

**Comment by GoliathLabs** [comment]
@blocktrron Hello, sorry for the long wait. You are right, dependabot creates PRs to updates for the enabled package ecosystems. As it is the case with PRs, they can be tested individually.

My suggestion would be to merge this PR. Dependabot will probably create PRs for updates regarding the gh actions used, the sphinx stack, etc.

These updates can be tested and if everything is approved, the Dependabot PR can be merged. Otherwise, it will remain in PR until someone tests the changes/updates.

**Comment by mweinelt** [comment]
I generally think dependabot is a positive thing, because it takes away work that usually gets forgotten.

**Comment by NeoRaider** [comment]
I don't think the bot should set any assignees or reviewers - we will see the PRs anyways and deal with it as time permits.

**Comment by GoliathLabs** [comment]
@NeoRaider @mweinelt Removed Reviewers & assignees :)

**Pull request merged**
