### PR TITLE
ipq807x-generic: add support for Xiaomi R-3600

### PR DESCRIPTION
**Pull request by Djfe**
also known as Mi AIoT Router AX3600

Thanks to _madez_ for providing the hardware :)

- [x] Must be flashable from vendor firmware
  - [ ] Web interface
  - [ ] TFTP
  - [x] Other: [see wiki for details](https://openwrt.org/toh/xiaomi/ax3600#installation)
       - first obtain ssh access (hack)
       - then flash openwrt `initramfs-factory.ubi` via ubiformat
       - then `sysupgrade -n` to gluon
- [x] Must support upgrade mechanism
  - [x] Must have working sysupgrade
    - [x] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [x] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
        xiaomi-ax3600
- [x] Reset/~~WPS/...~~ button must return device into config mode
- [x] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
      28:d1:27:fc:a6:2c
  - ~~When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.~~
- Wired network
  - [x] should support all network ports on the device
  - [x] must have correct port assignment (WAN/LAN)
    - ~~if there are multiple ports but no WAN port:~~
      - ~~the PoE input should be WAN, all other ports LAN~~
      - ~~otherwise the first port should be declared as WAN, all other ports LAN~~
- Wireless network (if applicable)
  - [x] Association with AP must be possible on all radios
  - [x] Association with 802.11s mesh must work on all radios 
  - [x] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [x] Lit while the device is on
    - [x] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - ~~Radio LEDs~~
    - [ ] ~~Should map to their respective radio~~
    - [ ] ~~Should show activity~~
  - Switch port LEDs
    - [x] Should map to their respective port (or switch, if only one led present) 
    - [x] Should show link state and activity
- ~~Outdoor devices only:~~
  - [ ] ~~Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
- ~~Cellular devices only:~~
  - [ ] ~~Added board name to `is_cellular_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`~~
  - [ ] ~~Added board name with modem setup function `setup_ncm_qmi` to `package/gluon-core/luasrc/lib/gluon/upgrade/250-cellular`~~
- Docs:
  - [x] Added Device to `docs/user/supported_devices.rst`

### CODE REVIEW

**Comment by Djfe** [comment]
two possible issues:
- Gluon Config mode > Advanced > Info says:
``Switch Typ: none`
- Primary MAC is ok, but device uses random macs for most interfaces
- I want to figure out how to do factory images for the target (if at all), currently building of Netgear WAX218 fails due to missing initramfs even with `factory = false,` being set.

**Comment by rotanid** [comment]
@Djfe have you tested this with latest openwrt changes and do you still want to work on this support?

**Comment by AiyionPrime** [comment]
@Djfe I built a firmware using your PR, wifi looks good.

I know that @cawi2001 would be available to test something, if there's something missing here.
The "IOT" triple radio is not worth waiting for (at least for this device) due to the ridiculous small possible throughput.

Deactivating it is very much fine, I'd say.

**Comment by Djfe** [comment]
👍
should we continue this discussion in #3354?

**Pull request closed without merging**
