### PR TITLE
config-mode: link to gluon commit id on GitHub

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by rotanid** [comment]
i'm not happy with that, as that might lead to a broken link for everyone using a gluon fork with own release tags, if i'm not mistaken?
e.g. on our stable firmware, /lib/gluon/gluon-version currently contains "gluon-v2016.1.5-tecff-2"

**Comment by rubo77** [comment]
This should be cleared up when this problem is solved: https://github.com/freifunk-gluon/gluon/issues/917#issuecomment-260170068

**Comment by rubo77** [comment]
The problem was not, that I didn't use annotated tags. It is fine, if the last release is taken as the last annotated tag, so the problem in my repo was (like i've seen iin many others) that the tags that were released in the main gluon repo were not pushed to the local repository with

    git push --follow-tags

now everything porks fine in my gluon build server.

before:

    $ git describe --always
    v2015.1-686-g0f9a1a9

And now:

```
$ git pull
remote: Counting objects: 8, done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 8
Unpacking objects: 100% (8/8), done.
From https://github.com/rubo77/gluon
 * [new tag]         v2016.1    -> v2016.1
 * [new tag]         v2016.1.1  -> v2016.1.1
 * [new tag]         v2016.1.2  -> v2016.1.2
 * [new tag]         v2016.1.3  -> v2016.1.3
 * [new tag]         v2016.1.4  -> v2016.1.4
 * [new tag]         v2016.1.5  -> v2016.1.5
 * [new tag]         v2016.2    -> v2016.2
 * [new tag]         v2016.2.1  -> v2016.2.1
Already up-to-date.

$ git describe --always
v2016.2.1-3-g0f9a1a9
```

**Comment by NeoRaider** [comment]
I agree with @rotanid, this is a bad idea.

**Comment by rotanid** [comment]
@rubo77 just to clarify: the commit id you have at the end of your version number isn't there, if you are using a tagged release without any changes to it. therefore my and neoraiders concerns.

**Comment by rubo77** [comment]
If the end doesn't end with `...g<commit_id>` then the link could lead directly to the main gluon release (gluon-version)

an unsolveable problem would only occur, if someone builds a firmware based on a gluon repository, and has new commits that are not hosted on github any more

**Comment by rotanid** [comment]
what if someone builds a firmware based on his own gluon fork with additional new commits after a tag? these commit ids wont work with the hard coded link to upstream gluon...

**Comment by rubo77** [comment]
If we would save the used git remote on the routers in /lib/gluon/used_repository we could link to the right source for each commit

**Pull request closed without merging**
