### PR TITLE
ipq40xx: add support for ZyXEL NBG6617

### PR DESCRIPTION
**Pull request by blocktrron**
As discussed with neoraider, this device is eligible for a backport
 - Better CPU / WiFi than Archer C7
 - ~10 € cheaper
 - Flashable via Web-IF

## Device checklist
 - [x] must be flashable from vendor firmware
     - [x] webinterface
     - [x] tftp
 - must support upgrade mechanism
     - [x] must have working sysupgrade
     - [x] must keep/forget configuration (if applicable)
     - [x] must have working autoupdate
```
root@64xxx-b8eca3d6884c:~# lua -e 'print(require("platform_info").get_image_name())'
zyxel-nbg6617
```
 - wired network
     - [x] should support all network ports on the device
     - [x] must have correct port assignment (WAN/LAN)

 - wifi (if applicable)
     - [x] association with AP must be possible on all radios
     - [x] association with 802.11s mesh must be working on all radios
     - [x] ap/mesh mode must work in parallel on all radios

- led mapping
     - [x] power/sys led
         - [x] lit while the device is on
         - [x] should display config mode blink sequence (https://gluon.readthedocs.io/en/latest/features/configmode.html)
    - radio leds
         - [x] should map to their respective radio
         - [x] should show activity
     - switchport leds
         - [x] should map to their respective port (or switch, if only one led present)
         - [x] should show link state and activity

- [x] reset/wps button must return device into config mode
- [x] primary mac should match address on device label (or packaging) (https://gluon.readthedocs.io/en/latest/dev/hardware.html#notes)
 - Device has multiple MACs printed on case - NodeID refers to WiFi 2.4GHz

### CODE REVIEW

**Comment by achterin** [comment]
Please add an entry for this device to the supported device list as well.

**Comment by blocktrron** [comment]
fixed

**Comment by rotanid** [comment]
not yet accepted or not even sent upstream?
btw, maybe it would make it easier for someone if you link the upstream commit ids in your PR, in case someone wants to port them to 18.06

**Comment by blocktrron** [comment]
@rotanid  Just sent the patch to upstream: https://patchwork.ozlabs.org/patch/992750/

**Comment by belzebub40k** [comment]
The LED patch is now upstream https://github.com/openwrt/openwrt/commit/5896b146a49968aa0a9889f57f75a8a918e384ae

**Comment by mweinelt** [comment]
Upstream yes, but not in openwrt-18.06. If it's not backported there we would need to keep the patch downstream until we move to 19.01

**Pull request merged**
