### PR TITLE
backport: Futro support in x86-generic

### PR DESCRIPTION
**Pull request by kaechele**
Signed-off-by: Felix Kaechele <felix@kaechele.ca>

### CODE REVIEW

**Comment by kaechele** [comment]
Fixes https://github.com/freifunk-gluon/gluon/issues/490

**Comment by A-Kasper** [comment]
I think this should be ported to the 64bit architecture

**Comment by kaechele** [comment]
This is just a backport of what is in upstream OpenWrt.
Upstream declined adding this to the x86-64 target as well following a discussion here: https://lists.openwrt.org/pipermail/openwrt-devel/2015-September/036155.html
I don't have any ambitions to port this to 64 bit as I don't see the immediate benefit for my use of the Futro as a fastd offloader.

**Comment by A-Kasper** [comment]
Am 24.11.2015 um 18:32 schrieb Felix Kaechele:
> This is just a backport of what is in upstream OpenWrt.
> Upstream declined adding this to the x86-64 target as well following a
> discussion here:
> https://lists.openwrt.org/pipermail/openwrt-devel/2015-September/036155.html
> I don't have any ambitions to port this to 64 bit as I don't see the
> immediate benefit for my use of the Futro as a fastd offloader.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freifunk-gluon/gluon/pull/567#issuecomment-159349621>.

It's just one line. I'll test it.
I'm not sure if fastd maybe faster with 64Bit code. But why using 32 Bit
if 64 Bit is supported?!

**Comment by A-Kasper** [comment]
The test was successfull.
If you add the line
CONFIG_PATA_ATIIXP=y
to /target/linux/x86/64/config-default
the 64 Bit version works on Futros.
I still didn't found time to learn how to write patches, so I'm sorry that
I have to ask someone else to implement this patch.

2015-11-24 18:32 GMT+01:00 Felix Kaechele <notifications@github.com>:

**Comment by rotanid** [comment]
perhaps we could also add USB support, see https://forum.freifunk.net/t/f-a-q-zum-offloader-fujitsu-siemens-futro-s550/8294

**Comment by NeoRaider** [comment]
@rotanid, just add the USB support to site.mk.

**Comment by corny** [comment]
Is it possible to only add USB support to x86 images?

**Comment by mmalte** [comment]
Yes, just build them with a different site.mk

I'm using one branch for normal routes with offline ssid support and one branch with additional drivers for x86 versions.

**Comment by mmalte** [comment]
https://github.com/ffac/site?files=1

https://github.com/ffac/site/tree/x86?files=1

**Comment by NeoRaider** [comment]
You never need to provide target-specific site configs, just conditionalize parts of site.mk using
```
ifeq ($(GLUON_TARGET),x86-generic)
...
endif
```

**Comment by corny** [comment]
Oh, great - that `ifeq ... endif` is exactly what I was looking for.

**Comment by NeoRaider** [comment]
@kaechele, can you rebase this onto the current master?

**Comment by kaechele** [comment]
OK like this? Or do you want me to start a new, clean branch?

**Comment by A-Kasper** [comment]
saame should be done for 64 branch. some futros are using 64 bit.
Am 08.02.2016 11:39 schrieb "Felix Kaechele" <notifications@github.com>:

**Comment by NeoRaider** [comment]
@kaechele, I have no idea what you have done, but now it is completely broken. Please rebase it so there's just a single commit on top of current master.

**Comment by kaechele** [comment]
Strange. I rebased the branch and pushed to my repo and it just added all the commits to the pull request.
Sometimes git is awfully strange if you don't do it 100% the way you (probably) should have.
I'll open a new pull request.

**Comment by NeoRaider** [comment]
Ah, you probably rebased our master on top of your branch, instead of the other way around...

**Pull request closed without merging**
