### PR TITLE
ramips-mt76x8: add support for TP-Link Archer C50 v6

### PR DESCRIPTION
**Pull request by GoliathLabs**
- [X] Must be flashable from vendor firmware
  - [X] Web interface
  - [X] TFTP
  - [ ] Other: 
- [X] Must support upgrade mechanism
  - [X] Must have working sysupgrade
    - [X] Must keep/forget configuration (`sysupgrade [-n]`, `firstboot`)
  - [X] Gluon profile name matches autoupdater image name
        (`lua -e 'print(require("platform_info").get_image_name())'`)
- [X] Reset/WPS/... button must return device into config mode
- [X] Primary MAC address should match address on device label (or packaging)
      (https://gluon.readthedocs.io/en/latest/dev/hardware.html#hardware-support-in-packages)
  - When re-adding a device that was supported by an earlier version of Gluon, a
    factory reset must be performed before checking the primary MAC address, as
    the setting from the old version is not reset otherwise.
- Wired network
  - [X] should support all network ports on the device
  - [X] must have correct port assignment (WAN/LAN)
    - On devices supplied via PoE, there is usually no explicit WAN/LAN labeling on the hardware.
      The PoE input should be the WAN port in this case.
- Wireless network (if applicable)
  - [X] Association with AP must be possible on all radios
  - [X] Association with 802.11s mesh must work on all radios 
  - [X] AP+mesh mode must work in parallel on all radios
- LED mapping
  - Power/system LED
    - [X] Lit while the device is on
    - [X] Should display config mode blink sequence 
          (https://gluon.readthedocs.io/en/latest/features/configmode.html)
  - Radio LEDs
    - [X] Should map to their respective radio 
    - [X] Should show activity
  - Switch port LEDs
    - [X] Should map to their respective port (or switch, if only one led present) 
    - [X] Should show link state and activity
- Outdoor devices only:
  - [ ] Added board name to `is_outdoor_device` function in `package/gluon-core/luasrc/usr/lib/lua/gluon/platform.lua`
- Docs:
  - [X] Added Device to `docs/user/supported_devices.rst`

### CODE REVIEW

**Comment by GoliathLabs** [comment]
The upstream PR has to be merged first: https://github.com/openwrt/openwrt/pull/13547

PR has been tested properly with FFMUC

**Comment by herbetom** [comment]
I would suggest marking this PR a draft until a Review can happen.

**Comment by GoliathLabs** [comment]
I no longer have the device. I did the testing for another party. I'll try to get our firmware built to get it tested out properly

**Comment by GoliathLabs** [comment]
Upstream has been merged. This can now be merged

**Comment by rotanid** [comment]
@GoliathLabs it has to be in the 23.05 branch of OpenWrt

**Comment by blocktrron** [comment]
@rotanid I'd be for closing this PR, as the device testing does not seem to be conducted using any state present in upstream nor this PR.

This is until the device is backported upstream and re-tested with the respective upstream state.

**Comment by blocktrron** [comment]
@GoliathLabs All communication regarding this PR is in this very PR, so please explain where i did not communicate correctly or left you out of the discussion?

I've  outlined the requirements in the last sentence of my last comment.

> This is until the device is backported upstream and re-tested with the respective upstream state.

**Comment by trixmoe** [comment]
FYI, this device (Archer C50 v6) was added in OpenWrt 24.10.
Note that this excludes the Archer C50 v6 ES version, which is apparently a rebranded C54.

Freifunk Luxembourg owns at least one, possibly a few, which I can (get someone to) use for testing if needed.
I don't have one personally, but I can get my hands on one if more work is needed than just testing.

https://openwrt.org/toh/hwdata/tp-link/tp-link_archer_c50_v6
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=e9ac1b19e0f3d383ab83373c261bfb5527a29521

**Comment by GoliathLabs** [comment]
I was going to revive this PR again, as got my hands on one C50 V6 again.

**Comment by GoliathLabs** [comment]
https://github.com/freifunk-gluon/gluon/pull/3568

I only got one minor problem with the autoupdater. everything else seems to work now.

**Pull request closed without merging**
