### PR TITLE
C indentation

### PR DESCRIPTION
**Pull request by AiyionPrime**
@lemoer suggested to break #2747 into two parts.
So this is the simple one, that should be about as easy (and annoying) to review as the PR's @rotanid reviewed in the last days. Thanks :/

### CODE REVIEW

**Comment by rotanid** [comment]
as i have no experience whatsoever with C and if there are any rules regarding indentation, i have to decline this review request.

**Review by lemoer — APPROVED** [review]
LGTM.

**Comment by AiyionPrime** [comment]
Rebased onto master due to merged spellfix commit.

**Comment by NeoRaider** [comment]
This PR should also update the style of all `.h` files.

**Comment by AiyionPrime** [comment]
> This PR should also update the style of all `.h` files.

I thought so too, that's why they are included in this PR as well.
Missing anything in particular?

The editorconfig-checker is running successfully on these changes.

**Review by blocktrron — APPROVED** [review]

**Comment by NeoRaider** [comment]
> > This PR should also update the style of all `.h` files.
> 
> I thought so too, that's why they are included in this PR as well. Missing anything in particular?
> 
> The editorconfig-checker is running successfully on these changes.

Hmm, I guess I got confused by my clang-format experiments. There are a few files like `./gluon-ebtables-limit-arp/src/lookup3.h` with very weird formatting, but we can leave that for later and just make the editorconfig check pass with this PR.

**Pull request merged**
