### PR TITLE
docs: danish language support in configmode

### PR DESCRIPTION
**Pull request by do9xe**
Sven and a friend of mine translated and corrected the danish version of the config mode. We will also try to translate the expermode.

### CODE REVIEW

**Comment by NeoRaider** [comment]
Any updates here?

**Comment by svenfl** [comment]
I'll do the updates this weekend. In the past the da language packet of gluon didn't work because Danish language support was missing in Openwrt

**Comment by rotanid** [comment]
@svenfl are you still planning on updating this PR or creating a new one (as this one is owned by someone else) ?

**Comment by svenfl** [comment]
This pull request is obsolete now. The new one is now #832

**Comment by NeoRaider** [comment]
Replaced by #832.

**Pull request closed without merging**
