### PR TITLE
set alias to raspberry-pi-model-b-rev-2

### PR DESCRIPTION
**Pull request by 2tata**
Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>

``` bash
Downloading 'http://autoupdate-lede.ffnw/stable/stable.manifest'
Connecting to 2a01:4f8:150:50a2::107:80
Writing to stdout

-                    100% |*******************************| 61344   0:00:00 ETA
Download completed (61344 bytes)
No matching firmware found (model raspberry-pi-model-b-rev-2)
No usable mirror found.
```

### CODE REVIEW

**Comment by NeoRaider** [comment]
I think it's better to use *manifest_alias* here instead of *alias*, no need to actually create symlinks.

Looking at `/lib/brcm2708.sh`, there are a lot more possible names... this might even warrant switching to *board_name* instead of *model* as basis for the brcm2708 image names eventually. (See also: related thread on the lede-dev ML regarding image naming. Maybe we will soon have a more robust solution for choosing the correct image, when that discussion has come to a conclusion.)

**Comment by 2tata** [comment]
On 12/13/17 00:20, Matthias Schiffer wrote:
> I think it's better to use *manifest_alias* here instead of *alias*, no need to actually create symlinks.
> 
> Looking at `/lib/brcm2708.sh`, there are a lot more possible names... this might even warrant switching to *board_name* instead of *model* as basis for the brcm2708 image names eventually. (See also: related thread on the lede-dev ML regarding image naming. Maybe we will soon have a more robust solution for choosing the correct image, when that discussion has come to a conclusion.)
> 

Ay, thanks for that information. I have change it to *manifest_alias*

cheers
Tarek

**Comment by 2tata** [comment]
This MR is more a small hot-fix. It should be replace if a proper solution in LEDE is implemented.

**Comment by NeoRaider** [comment]
Merged with proper commit messages.

**Pull request closed without merging**
