### PR TITLE
modules: update to latest HEAD

### PR DESCRIPTION
**Pull request by herbetom**
This contains the patches i'll need for #2768 once I get around to working on it again (but could be a while).

### CODE REVIEW

**Comment by AiyionPrime** [comment]
Is this intended for the GL-XE300 in #2768?

**Comment by rotanid** [comment]
> Is this intended for the GL-XE300 in #2768?

that's what he wrote in the PR description, yes? ;-)

**Comment by AiyionPrime** [comment]
To tired. Thanks, goodnight.

Is this tested?

**Comment by herbetom** [comment]
> Is this tested?

Well, i've build myself an x86-64 image and booted it. If you interpret "tested" loosely, it may be. Otherwise, no, this is not tested.

**Comment by AiyionPrime** [comment]
I had hoped you tested whether your features work; but if it ran at all I'm fine with it.

**Comment by herbetom** [comment]
I did test the patches since they were backported to openwrt-2203 but that was with a smaller bump as can be seen in the XE300 PR.

**Pull request merged**
