### PR TITLE
Use LAN/WAN interfaces from board.json, add lantiq special case

### PR DESCRIPTION
**Pull request by NeoRaider**
Use the WAN port of switch0 instead of `dsl0` on lantiq devices where available. It would be great if we could test this on a few of our existing lantiq devices - I don't have any.

See also: https://github.com/freifunk-gluon/gluon/pull/2006#issuecomment-643479894

### CODE REVIEW

**Comment by blocktrron** [comment]
I'll be able to test this with a 7412 and 7312. However this might not be ideal, as they only have single LAN port.

**Comment by NeoRaider** [comment]
@blocktrron Well, it should at least not break anything for these devices then.

**Comment by 4ludwig4** [comment]
@NeoRaider I can test this with the [Arcadyan VGV7510KW22](https://openwrt.org/toh/arcadyan/vgv7510kw22) if it makes sense? Don't know so how to test this yet.

**Comment by NeoRaider** [comment]
@4ludwig4 Just rebase your change onto this branch and check if the WAN interface is assigned correctly after `sysupgrade -n` or `firstboot`.

**Comment by NeoRaider** [comment]
@blocktrron Did you have a chance to test this?

**Comment by 4ludwig4** [comment]
@NeoRaider I wrote a fix in #2006 for this which I'm currently building then testing as your code didn't work for my Arcadyan VGV7510KW22 (o2 Box 6431).

`elseif platform.match('lantiq') then`
Don't know if I should just limit this to my device instead of doing this for all lantiq devices. Or how do you usually know that this change is device wide?

**Comment by NeoRaider** [comment]
@4ludwig4 Thanks, your fix looks correct - I have updated my PR with a slightly modified version.

The whole lantiq platform uses the same code to set up the WAN interface in `board.json`, so the code should fine like this.

**Pull request merged**
