### PR TITLE
modules: update modules

### PR DESCRIPTION
**Pull request by blocktrron**
Update mainly because of 

97213c7335 mac80211: parse the correct set of HE capabilities for AP mode

### CODE REVIEW

**Comment by herbetom** [comment]
It seems like you didn't "pull" the latest changes before creating those commits (the log in the commit message is too long).

Should look more like:


```
    modules: update packages
    
    39943175a squid: bump to 4.17
    c15e924f1 dnscrypt-proxy2: update to version 2.1.2
    f1a15fd5b coova-chilli: Fix compile problem with _init()
    625f17633 mpd: update to 0.23.9
    900d42fbe mpd: update to 0.23.8
    257242799 pciutils: update to 3.8.0
    1e53ad688 travelmate: update 2.1.0
```

```
    modules: update openwrt
    
    97213c7335 mac80211: parse the correct set of HE capabilities for AP mode
```

**Comment by rotanid** [comment]
the commits should be fine, but the commit messages definitely aren't

**Comment by herbetom** [comment]
I've opened #2622 which should pass the CI checks.

**Comment by rotanid** [comment]
let's continue in #2622

**Pull request closed without merging**
