### PR TITLE
gluon-config-mesh-vpn: use default value for mesh-vpn enabled from site

### PR DESCRIPTION
**Pull request by christf**
auto-enable mesh-vpn checkbox in config manager when enabled in site.conf

### CODE REVIEW

**Comment by rotanid** [comment]
hm, i don't get it?
we have it enabled in site.conf and our user's see a already checked checkbox in config-mode.
what is left that your PR changes?

**Comment by christf** [comment]
for me the checkbox in the initial configuration was not enabled. This PR fixes that.

**Comment by rotanid** [comment]
hm, this is interesting.... @mweinelt ?

**Comment by NeoRaider** [comment]
This is definitely not the correct solution. We need to find out how the node can get into a state where gluon.mesh_vpn.enabled is not set correctly.

**Comment by christf** [comment]
I installed without taking

**Comment by rotanid** [comment]
> I installed a factory image not keeping settings.

via the config mode? via sysupgrade? i never used the factory image after there's no vendor image anymore... which device? maybe i can try to reproduce.

**Comment by edeso** [comment]
that sounds familiar. have a WR841N/ND v9 that i tftpd a v2018.2.2 factory image 
https://images.ffkbu.de/BonnV2/stable/FastD/factory/gluon-ffkbu-V2-v2018.2.2-FastD-tp-link-tl-wr841n-nd-v9.bin
to (aka tftp recovery) ended up with a wifi meshing node but no vpn upstream.

a little check turned out that fastd was disabled (fastd.mesh_vpn.enabled='0') on the new node. enabling it worked fine.

 i visited the config mode to setup the node, so i might have disabled meshing there by accident, but i'm pretty sure i didn't because i never did that before.

**Comment by NeoRaider** [comment]
I can't reproduce the issue with Gluon master on x86-64.

**Comment by christf** [comment]
I saw this with factory installs on ar71xx and with factory images for x86-generic.

**Comment by NeoRaider** [comment]
@christf Can you link such an x86 image?

**Comment by rubo77** [comment]
And what is the site config, you used for your build?

**Comment by christf** [comment]
hm. after fixing the boot hang issue with wireguard by moving the key generation into the init script I was not able to reproduce

**Comment by NeoRaider** [comment]
Closing, please open an issue if it reoccurs.

**Pull request closed without merging**
