### PR TITLE
Build system improvements

### PR DESCRIPTION
**Pull request by NeoRaider**
- Improve handling of build environment
- Simplify manifest generation using .ONESHELL
- Increase control over `feeds.conf` generation (supersedes #1933)
- Add (very incomplete) docs

### CODE REVIEW

**Comment by NeoRaider** [comment]
I've found one downside of .ONESHELL: `make -n` does not work as expected anymore, as both make and non-make commands are run in the same shell invocation (so some commands are run even with `-n`). I think the benefits outweigh the downsides though - I've never relied on `make -n` anyways.

**Comment by mweinelt** [comment]
The CI timed out for some reason 🤔 Maybe force-push for another run.

**Comment by blocktrron** [comment]
This needs a rebase

**Comment by NeoRaider** [comment]
Done

**Comment by mweinelt** [comment]
Rebase against master to have all targets built using GitHub Actions.

**Comment by mweinelt** [comment]
Rebased on top of master to have the latest CI fixes.

**Comment by mweinelt** [comment]
Tested and LGTM.

**Pull request merged**
