### PR TITLE
doc changes and release notes for release v2020.1.4

### PR DESCRIPTION
**Pull request by rotanid**
see also #2105

### CODE REVIEW

**Review by NeoRaider — CHANGES_REQUESTED** [review]
See my comments on the v2020.2.1 release note PR.

**Comment by rotanid** [comment]
> See my comments on the v2020.2.1 release note PR.

implemented.

**Review by NeoRaider — APPROVED** [review]

**Comment by rotanid** [comment]
does #2087 need to be backported to v2020.1.x @blocktrron ?

**Review by blocktrron — APPROVED** [review]
Doesn't need to be backported, as the size constraint is not a hard factor on v2020.1 as OpenSSL is not included with a Gluon feature.

**Pull request merged**
