### PR TITLE
RFC: gluon-mesh-vpn-*: make MTU of VPN device provider specific

### PR DESCRIPTION
**Pull request by lemoer**
If a community uses different vpn providers, they typically
assume the same MTU for the wan device underneath the VPN. As
different VPN providers however have different overhead, the MTU
of the VPN device differs for each provider. Therefore this
commit makes the MTU of the VPN device provider specific.

This has two advantages:
1. The same site.conf can used to bake firmwares for different
   VPN providers (only by selecting a diferent vpn feature in the
   site.mk).
2. We are coming closer to the option of integrating multiple VPN
   providers into one firmware.

### CODE REVIEW

**Comment by lemoer** [comment]
This is currently RFC. It's neither properly tested yet, neither the docs are adjusted. Feel free to comment.

If the idea is generally well accepted, I'll do the rest.

**Comment by lemoer** [comment]
The changes are now tested successfully and docs have been added.

**Comment by lemoer** [comment]
To adjust docs/user/site.rst, I rebased this PR on #2351 (which itself is rebased on #2349 and #2186).

**Comment by lemoer** [comment]
We just discussed on our RC3 meeting.

 @NeoRaider is against the move of the MTU. We need a third opinion here.

**Review by blocktrron — APPROVED** [review]

**Comment by blocktrron** [comment]
Discussed with @AiyionPrime and @lemoer , I'm in favor of merging this proposal, as the MTU is a property of the link which depends on the VPN protocol. Therefor, this change is logical to me.

**Pull request merged**
