### PR TITLE
added WR841v10 to device list

### PR DESCRIPTION
**Pull request by Tarnatos**

### CODE REVIEW

**Comment by NeoRaider** [comment]
Please add a "docs: " prefix to your commit message.

**Comment by Tarnatos** [comment]
I'm sorry baut how? I'm not very familar with github.

**Comment by NeoRaider** [comment]
I don't know if this is possible with Github either, I never use the web interface for editing. You can clone your branch, edit the commit message with `git commit --amend` and replace the branch on Github using `git push -f`.

**Comment by Tarnatos** [comment]
I'm sorry but i dont' understand how i works. Maybe someone other can do this ....

**Comment by NeoRaider** [comment]
I've adjusted and merged your patch.

**Pull request closed without merging**
