### PR TITLE
[master] [forward-port] docs: Add v2022.1.4 release notes

### PR DESCRIPTION
**Pull request by blocktrron**

### CODE REVIEW

**Review by AiyionPrime — APPROVED** [review]

**Review by herbetom — CHANGES_REQUESTED** [review]
Just for safety: This needs another force push with the actual commit ID from v2022.1.x

**Review by AiyionPrime — CHANGES_REQUESTED** [review]
@herbetom just pointed out, the referenced commit might be wrong one.

**Comment by blocktrron** [comment]
@AiyionPrime How come? https://github.com/blocktrron/gluon/commit/205e66c74367fdab13a29e03c8db0f1d1bc98831 is the one on v2022.1.x

**Comment by herbetom** [comment]
I had looked at the PR description. But yeah, seems like it's alreeady the correct in the commit.

**Comment by blocktrron** [comment]
GitHub auto-introduces the content from the commit, but it does not make it to the history. This is a nothingburger.

**Review by AiyionPrime — APPROVED** [review]
whatever nothingburgers are?

**edit** I see. https://en.wikipedia.org/wiki/Nothingburger

**Pull request merged**
